### ISSUE TITLE
Java Installation issue - can't find nodejavabridge_bindings.node 

### ISSUE THREAD

**Issue by PraneethKumar** [joeferner/node-java#108]
1) installed java using  "npm install java"
2) got below exception while running "ravi.js" which has Java API call in it.

D:\ravi>node ravi.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'D:\node_modules\java\build\Release\nodejavabridge_bindings.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\node_modules\java\lib\nodeJavaBridge.js:5:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

3) then tried to install above mentioned (missing) package "install nodejavabridge_bindings.node"

D:>npm install nodejavabridge_bindings.node
npm http GET https://registry.npmjs.org/nodejavabridge_bindings.node
npm http 404 https://registry.npmjs.org/nodejavabridge_bindings.node
npm ERR! 404 'nodejavabridge_bindings.node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "D:\Program Files\nodejs\\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "nodejavabridge_bindings.node"
npm ERR! cwd D:\
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\npm-debug.log
npm ERR! not ok code 0
D:>

4) Can you please advice how to get around it
and if possible the correct way to install/excecute Java / API

**Comment by jgajula** [comment]
Hi jsdevel,

I have the same problem as well. 

I have downloded java module in Mac OS , its working perfectly in my local, But when i deploy this in qa server, i get the following error. usually running npm install on qa should resolve this problem. But my QA server does not have access to internet or npm. How can i rebuild this java module for linux in Mac OS? or any other way to get around this issue. Thanks.


module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /usr/mware/tcServerAppDetails/VDPPortal/webapps/node_modules/java/build/Release/nodejavabridge_bindings.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/mware/tcServerAppDetails/VDPPortal/webapps/node_modules/java/lib/nodeJavaBridge.js:7:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by lordazzi** [comment]
Same here.... I need the full dependencies and softwares versions required...

C:\Users\2102204410\AppData\Roaming\npm\node_modules\java>if not defined npm_con
fig_node_gyp (node "C:\Users\2102204410\AppData\Roaming\nvm\v0.12.4\node_modules
\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  e
lse (rebuild)
Compilando os projetos desta solução um de cada vez. Para habilitar a compilação
 paralela, adicione a opção "/m".
  The following error has occurred during XML parsing:

  File: C:\Users\2102204410\AppData\Roaming\npm\node_modules\java\build\nodejav
  abridge_bindings.vcproj
  Line: 1
  Column: 5255
VCBUILD : error Message:  [C:\Users\2102204410\AppData\Roaming\npm\node_modules
\java\build\binding.sln]
  Erro de sistema: -2147154687.

  The file 'C:\Users\2102204410\AppData\Roaming\npm\node_modules\java\build\nod
  ejavabridge_bindings.vcproj' has failed to load.
gyp ERR! build error
gyp ERR! stack Error: `c:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\2102204410\AppData\Roaming\n
vm\v0.12.4\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\2102204410\\AppData\\Roaming\\nvm\\v0.12.4\\
node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\2102204410\AppData\Roaming\npm\node_modules\java
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "java" "-g"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! java@0.5.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.5.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\nodejava\npm-debug.log

**Comment by souravprakashjena** [comment]
@jsdevel  i am getting below error

D:\xyzFolder>node nodeServer
module.js:597
return process.dlopen(module, path._makeLong(filename));
^

Error: The specified module could not be found.
\?\D:\xyzFolder\node_modules\java\build\Release\nodejavabridge_bindings.node
at Error (native)
at Object.Module._extensions..node (module.js:597:18)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (D:\xyzFolder\node_modules\java\lib\nodeJavaBridge.js:21
:16)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)

**Node Version-6.9.1

Windows Version- win 7(64-bit)**

**Comment by ploissken** [comment]
I experienced the very same problem after changing my Dockerfile to another image. Reinstalling the node_modules folder solved the problem!
