### ISSUE TITLE
npm install java fails on windows 7 32 bits

### ISSUE THREAD

**Issue by StefanHoutzager** [joeferner/node-java#110]
The machine is 64 bits, I installed node 32 bits. Several other modules have been installed succesfully, like socket.io. I 
  I start win SDK 7.1 command prompt as admin. 
setenv.cmd /Release /x86
cd C:\Program Files (x86)\nodejs\node_modules
npm install java

Some LNK2001 errormessages appear (see below). Updating NMP's node-gyp (https://github.com/TooTallNate/node-gyp/issues/305) did not help.
What could be the problem, how could I solve this?

Output:
Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.1
.
Targeting Windows 7 x86 Release

C:\Windows\system32>cd C:\Program Files (x86)\nodejs\node_modules

C:\Program Files (x86)\nodejs\node_modules>npm install java
npm WARN package.json RealTimeWebChat@0.0.0 No repository field.
npm WARN package.json RealTimeWebChat@0.0.0 No README data
npm http GET https://registry.npmjs.org/java
npm http 304 https://registry.npmjs.org/java
npm http GET https://registry.npmjs.org/find-java-home/0.0.6
npm http 304 https://registry.npmjs.org/find-java-home/0.0.6
npm http GET https://registry.npmjs.org/find-in-path
npm http 304 https://registry.npmjs.org/find-in-path

> java@0.3.1 install C:\Program Files (x86)\nodejs\node_modules\java
> node-gyp rebuild

C:\Program Files (x86)\nodejs\node_modules\java>node "C:\Program Files (x86)\nod
ejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.
js" rebuild
De projecten in deze oplossingen worden één voor één opgebouwd. Als u parallelle
 bouwbewerkingen wilt inschakelen, gebruikt u de schakeloptie /m.
  Verify Deps
  java.cpp
  javaObject.cpp
  javaScope.cpp
  methodCallBaton.cpp
  nodeJavaBridge.cpp
  utils.cpp
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabr
idge_bindings.vcxproj]
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabr
idge_bindings.vcxproj]
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabr
idge_bindings.vcxproj]
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabr
idge_bindings.vcxproj]
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabr
idge_bindings.vcxproj]
..\src\utils.cpp(496): warning C4800: 'jboolean' : forcing value to bool 'true'
 or 'false' (performance warning) [C:\Program Files (x86)\nodejs\node_modules\j
ava\build\nodejavabridge_bindings.vcxproj]
..\src\utils.cpp(579): warning C4800: 'jboolean' : forcing value to bool 'true'
 or 'false' (performance warning) [C:\Program Files (x86)\nodejs\node_modules\j
ava\build\nodejavabridge_bindings.vcxproj]
..\src\utils.cpp(598): warning C4244: 'argument' : conversion from 'jlong' to '
double', possible loss of data [C:\Program Files (x86)\nodejs\node_modules\java
\build\nodejavabridge_bindings.vcxproj]
C:\Users\Stefan.node-gyp\0.10.26\deps\v8\include\v8.h(184): warning C4506: no
definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Ha
ndle<T>)' [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabridge
_bindings.vcxproj]
          with
          [
              T=v8::Object
          ]
..\src\java.cpp(884): warning C4800: 'jboolean' : forcing value to bool 'true'
or 'false' (performance warning) [C:\Program Files (x86)\nodejs\node_modules\ja
va\build\nodejavabridge_bindings.vcxproj]
C:\Users\Stefan.node-gyp\0.10.26\deps\v8\include\v8.h(184): warning C4506: no
definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Ha
ndle<T>)' [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabridge
_bindings.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Users\Stefan.node-gyp\0.10.26\deps\v8\include\v8.h(179): warning C4506: no
definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Ha
ndle<T>)' [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabridge
_bindings.vcxproj]
          with
          [
              T=v8::Object
          ]
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\utility(142): wa
rning C4506: no definition for inline function 'v8::Persistent<T> v8::Persisten
t<T>::New(v8::Handle<T>)' [C:\Program Files (x86)\nodejs\node_modules\java\buil
d\nodejavabridge_bindings.vcxproj]
          with
          [
              T=v8::Object
          ]
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\utility(142): wa
rning C4506: no definition for inline function 'v8::Persistent<T> v8::Persisten
t<T>::New(v8::Handle<T>)' [C:\Program Files (x86)\nodejs\node_modules\java\buil
d\nodejavabridge_bindings.vcxproj]
          with
          [
              T=v8::FunctionTemplate
          ]
C:\Users\Stefan.node-gyp\0.10.26\deps\v8\include\v8.h(218): warning C4506: no
definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Ha
ndle<T>)' [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabridge
_bindings.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\Users\Stefan.node-gyp\0.10.26\deps\v8\include\v8.h(218): warning C4506: no
definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Ha
ndle<T>)' [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabridge
_bindings.vcxproj]
          with
          [
              T=v8::FunctionTemplate
          ]
     Creating library C:\Program Files (x86)\nodejs\node_modules\java\build\Rel
  ease\nodejavabridge_bindings.lib and object C:\Program Files (x86)\nodejs\nod
  e_modules\java\build\Release\nodejavabridge_bindings.exp
java.obj : error LNK2001: unresolved external symbol __imp__JNI_CreateJavaVM@12
 [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabridge_bindings
.vcxproj]
java.obj : error LNK2001: unresolved external symbol __imp__JNI_GetDefaultJavaV
MInitArgs@4 [C:\Program Files (x86)\nodejs\node_modules\java\build\nodejavabrid
ge_bindings.vcxproj]
C:\Program Files (x86)\nodejs\node_modules\java\build\Release\nodejavabridge_bi
ndings.node : fatal error LNK1120: 2 unresolved externals [C:\Program Files (x8
6)\nodejs\node_modules\java\build\nodejavabridge_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files (x86)\nodejs\node_modules\npm\nod
e_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files (x86)\nodejs\node_modules\java
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm ERR! java@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.3.1 install script.
npm ERR! This is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program File
s (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "java"
npm ERR! cwd C:\Program Files (x86)\nodejs\node_modules
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Program Files (x86)\nodejs\node_modules\npm-debug.log
npm ERR! not ok code 0

C:\Program Files (x86)\nodejs\node_modules>

**Comment by Slapbox** [comment]
I'm getting the error ` error LNK2001: unresolved external symbol __imp_JNI_CreateJavaVM` on Windows 7 64 bit running SDK 8u112. The SDK is 32 bit. Any ideas?

**Comment by fatbatman** [comment]
Same as Slapbox above LNK2001 errors with 32 JDK

**Comment by Sangz2020** [comment]
hi,

I could resolve same issue by doing below steps, make sure you have 32 bit JDK and JRE (i have used JDK and JRE 8) and 32 bit Node.

I had 64 bit JDK, uninstalled and later installed 32 bit JDK(X86) and JRE (Client VM)

 # run in administrator privileged command prompt window 


npm install --global --production windows-build-tools 

 npm update 

 npm install java

**Comment by stefanKuijers** [comment]
@jsdevel Sadly I still face the same issues. I uninstalled all versions of Java and Android Studio and after that installed the 32bit version of JDK 8.1. 

Same as @Slapbox and @fatbatman. Did anybody find the solution already?

I can [verify that I am running](https://stackoverflow.com/questions/2062020/how-can-i-tell-if-im-running-in-64-bit-jvm-or-32-bit-jvm-from-within-a-program) the 32bit version like this
```$ java -d64 -version
Error: This Java instance does not support a 64-bit JVM.
```
```$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) Client VM (build 25.144-b01, mixed mode)
```

Still When I run ```yarn add java``` or ```npm install --save java``` I recieve the same error.
``` error LNK2001: unresolved external symbol __imp_JNI_CreateJavaVM ``` 
and additionally:
```error LNK1120: 1 unresolved externals```

Before this error I have a truck load of warnings but I assume that this is not cause of the fail. Example warning:
``` warning C4996: 'v8::Function::NewInstance': was declared
deprecated```

The suggested solution of @Sangz2020 did not change anything. 

Does anybody have any thoughts on this?
