### ISSUE TITLE
npm install java fails

### ISSUE THREAD

**Issue by smartmouse** [joeferner/node-java#136]
Hello: do you know what could be wrong?
Does this support java version "1.7.0"?

Thanks in advance for your help

$ npm install java

 java@0.3.6 install /usr/nodebot/javaTest/node_modules/java

> node-gyp rebuild

make: Entering directory `/usr/nodebot/javaTest/node_modules/java/build'
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/javaObject.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/javaScope.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/methodCallBaton.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/nodeJavaBridge.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/utils.o
  SOLINK_MODULE(target) Release/obj.target/nodejavabridge_bindings.node
/usr/bin/ld: cannot find -ljvm
collect2: ld returned 1 exit status
make: *** [Release/obj.target/nodejavabridge_bindings.node] Error 1
make: Leaving directory`/usr/nodebot/javaTest/node_modules/java/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodebot/SVT31/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:268:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 2.6.32-431.17.1.el6.s390x
gyp ERR! command "node" "/home/nodebot/SVT31/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/nodebot/javaTest/node_modules/java
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm ERR! java@0.3.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.3.6 install script.
npm ERR! This is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-431.17.1.el6.s390x
npm ERR! command "/home/nodebot/SVT31/bin/node" "/home/nodebot/ISVT31/bin/npm" "install" "java"
npm ERR! cwd /usr/nodebot/javaTest
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/nodebot/javaTest/npm-debug.log
npm ERR! not ok code 0

**Comment by DonavanMartin** [comment]
Same error for me: 
-Raspberry Pi 3 model B
- node -v : v9.2.1
- npm -v : 1.4.21
