### ISSUE TITLE
java.lang.NullPointerException when creating object

### ISSUE THREAD

**Issue by lukouko** [joeferner/node-java#182]
I'm trying to use node-java to connect to a Tibco ESB instance. As a simple test, I'm just using a basic script to test connectivity:
```
var self = this;

try {
  self.connFactory = java.newInstanceSync("com.tibco.tibjms.TibjmsConnectionFactory");
  self.connFactory.setServerUrl(config.serverURL);
            
  self.connFactory.createConnection(config.username, config.password, function (err, connectionObj) {
    if (err) throw err;
    console.log("Connection established ok");

    // Not using callback on success just for testing purposes to keep node running. 
  });
}
catch (ex) {
  self.shutdown();
  cb(new Error(ex));
}
```
 It works most of the time (I see the connection established ok message), but on occasion it fails with the following stack dump:
```
java.lang.NullPointerException     
 at com.tibco.tibjms.TibjmsxCFImpl._createConnection(TibjmsxCFImpl.java:2
56)
 at com.tibco.tibjms.TibjmsConnectionFactory.createConnection(TibjmsConne
ctionFactory.java:58)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
```
It seems to be a random failure. I've confirmed via tibco admin tools that the tibco server has an active connection when the console log is received (as expected). I've also confirmed that the connection is correctly cleaned up when I stop the script (control+c). On failure cases, no connection is established.

I've tried lots of different combinations of sync/async calls, all with the same weird random failure. My current theory is that garbage collection is clearing away the connection factory instance from the JVM before it gets a chance to execute the create connection call. But that's pretty much just a theory based on my complete loss to explain the random nature of the failure.

Here are my environment details:
```
C:\>ver
Microsoft Windows [Version 6.3.9600]

C:\>java -version
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

C:\>node -v
v0.10.33
```
The java module has the following class paths pushed to it:
```
jms-1.1.jar
tibjms-6.3.0.jar
```

Some Tibco documentation can be found here:
https://docs.tibco.com/pub/enterprise_message_service/7.0.1-march-2013/doc/html/tib_ems_api_reference/api/javadoc/javax/jms/ConnectionFactory.html

Ideas appreciated. Thanks.

**Comment by joeferner** [comment]
Looks like setServerUrl needs the Sync suffix.

**Comment by lukouko** [comment]
Thanks, I'm not sure how I missed that, i'll give it a try in a little bit and report back. I suspect that will solve the problem given the symptoms.

**Comment by lukouko** [comment]
That solved the problem as expected. Thanks.

**Comment by karocksjoeli** [comment]
Hi ~ could you shared how you done this ? 
I am trying to connect to TIBCO using JMS as well

**Comment by lukouko** [comment]
Hi @karocksjoeli 

This is a really old problem I had, I haven't coded using the java bridge for years now.

From memory, node-java creates both async and sync method wrappers for the underlying methods for the java instance being initialised. In my issue, I attempted to use an async method (no sync suffix) without providing a callback to handle the async result, meaning that the serverURL would never be set before attempting a connection.

The solution was to simply add the sync suffix to the set server url method call:

```
var self = this;

try {
  self.connFactory = java.newInstanceSync("com.tibco.tibjms.TibjmsConnectionFactory");
  self.connFactory.setServerUrlSync(config.serverURL);

  self.connFactory.createConnection(config.username, config.password, function (err, connectionObj) {
    if (err) throw err;
    console.log("Connection established ok");

    // Not using callback on success just for testing purposes to keep node running. 
  });
}
catch (ex) {
  self.shutdown();
  cb(new Error(ex));
}
```

It's worth mentioning the code above is quite ancient and you'd be better off using node-java's support for promises and also ES6+ capabilities.

E.g.

```
const TIBJCO_JMS_CLASS = 'com.tibco.tibjms.TibjmsConnectionFactory';
let connectionFactory;
let connection;

async function connect({ serverUrl, username, password }) {
  try {
    // Prevent multiple connection creation
    if (connection) return;

    connectionFactory = await java.newInstancePromise(TIBCO_JMS_CLASS);
    await connectionFactory.setServerUrlPromise(serverUrl);
    connection = await connectionFactory.createConnectionPromise(username, password);

    console.log("Connection established ok");
  } catch (err) {
    throw err;
  }
}

module.exports = {
  connect,
};

```

I haven't tested the above code and it will rely on promise setup in the node-java module.

**Comment by karocksjoeli** [comment]
@lukouko much appreciate your time and experience share : )
