### ISSUE TITLE
how to call enum

### ISSUE THREAD

**Issue by coolme200** [joeferner/node-java#183]
i try to call enum 

but only return `{}`

**Comment by joeferner** [comment]
Can you provide an example.

**Comment by coolme200** [comment]
```
var test = java.import('com.TestEnum');
console.log(test.USER_TYPE);   ==>   {}
console.log(test.valuesSync());   ==> [ {} ]
```

**Comment by joeferner** [comment]
I see, yes this is a little misleading with node-java. Try calling ```console.log(test.USER_TYPE.toStringSync());``` and ```console.log(test.valuesSync().toStringSync());```
