### ISSUE TITLE
Remove support for JDK 1.6

### ISSUE THREAD

**Issue by joeferner** [joeferner/node-java#188]

**Comment by joeferner** [comment]
Not sure if there is anywhere else other than compile-java-code.sh and .travis.yml to remove jdk 1.6.

see https://github.com/joeferner/node-java/commit/20d6e0436d7f58fbc046c6f427c01d63b411d5fd

**Comment by jimlloyd** [comment]
@joeferner You should probably recompile the java sources with the modification to compile-java-code.sh and then commit the changed .class files.

Also, compile-java-code.sh still references jdk1.6 with: `-bootclasspath /opt/jdk1.6.0_45/jre/lib/rt.jar`

That reference to /opt/jdk1.6.0_45/... seems to be specific to the development machine you use. I created compile-java8-code.sh such that it assumes it is being run on a Mac. Do you also have a Mac for development? If so, perhaps we should unify? We could then rewrite compile-java-code.sh to look like the following, which eliminates the need for the -bootclasspath option, and ensures that we compile with JDK7 even if our dev machine is currenty configured for JDK8 development.

```
#!/bin/bash -e

JAVA_VERSION=1.7
JDK7_HOME=$(/usr/libexec/java_home -v ${JAVA_VERSION})

cd test
${JDK7_HOME}/bin/javac -source ${JAVA_VERSION} *.java

cd ../src-java/node
${JDK7_HOME}/bin/javac -source ${JAVA_VERSION} *.java

cd ../../
${JDK7_HOME}/bin/javah -classpath src-java -d ./src node.NodeDynamicProxyClass
```

Finally, there is a reference to 1.6 in the README.md (under the section on wrote on Java 8).

**Comment by joeferner** [comment]
No I'm using ubuntu. But we should be able to unify the scripts using a platform test using uname.
