### ISSUE TITLE
Fatal Error: Unable to find package java.lang in classpath or bootclasspath

### ISSUE THREAD

**Issue by iritesh** [joeferner/node-java#195]
i am trying to use node-java package.first i run command

npm install java

after that i cloned source code of this library.
i went to node-java directory using 
cd node-java

then run command ./compile-java-code.sh and getting error

Fatal Error: Unable to find package java.lang in classpath or bootclasspath

i am using ubuntu 12.04 64 bit. when i run command 
java -version its returning 

java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~precise1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

and when i run command javac -version its returning 
javac 1.7.0_75

perhaps its require some additional environment configuration.How to handle this issue.Please guideline.

**Comment by iritesh** [comment]
i copy pasted file rt.jar file in /opt/jdk/jre/lib/rt.jar now not facing this error.perhaps someone get help.

**Comment by AnnamrajuSarvani** [comment]
Hi 
I am new to this how do this? can you please this in details because I am having issue when I compile manually.

**Comment by musasesay** [comment]
Somehow the JDK language jars were removed from the classpath. All I had to do was reapply the JSDK home path.

Goto: 
File -> Project Structure -> Platform Settings -> SDKs
Re-apply the JSDK home path. 

Doing this added about 15 jars to the classpath. Apparently these are important for compiling.
