### ISSUE TITLE
Include multiple jars from a folder into the classpath

### ISSUE THREAD

**Issue by gyandeeps** [joeferner/node-java#197]
My use case was that I wanted to load like more than 20 jars to the class path. How I did was I read all the files in the directory and then pushed each one individually like this:

```.js
fs.readdirSync(path.resolve(__dirname, "./millennium/dependency")).forEach(function(file){
    java.classpath.push(path.resolve(__dirname, "./millennium/dependency", file));
});
```

I thik what I am looking for is that we should be able to use the `java` option to say include this directory path my classpath and it should pick up all the jars from it. something like this:

```.js
java.options.push("classpath=<some directory>");
```

**Comment by joeferner** [comment]
added `java.classpath.pushDir('lib')`
