### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by zalym** [joeferner/node-java#203]
Hello

I am trying to use this wonderful library to create a solace bridge as solace doesn't support NodeJS in its older versions.  

So I create an adapter that does the heavy lifting of doing the solace connections etc, and then expose an interface that would act as the bridge to Node, for e.g.:  one method to consume the messages I receive from Solace and another to send to Solace.

My problem is that the connection method is correctly being called from Solace, but after that, nothing happens.  

What are my options to turn on debugging for this library?

Thanks
Saleem

**Comment by jimlloyd** [comment]
Are you sure that you're using the correct function name for either the sync or async behavior you want? One common mistake is to use exactly the name of the method you want to call, but expecting the method to execute synchronously. You must either add the Sync suffix to your method name, or add a callback as the last argument.  (Or use the new [asyncOptions feature](https://github.com/joeferner/node-java#asyncoptions-control-over-the-generation-of-sync-async--promise-method-variants) to change the default behavior).

**Comment by zalym** [comment]
The flow is as follows:  
My adapter(java) requires an EventHandler, which is implemented in Node.  The methods are connect, disconnect, messageReceived and messageSent.  I call the adapter's connect method and it duly connects to solace and calls the event handler's method, which in turn calls my node method.  Then I send a message by calling the adapter's method, and it duly calls the node method.  What is not happening is the callback within java, where it is listening to messages from the appliance, and then duly notifies node.  That flow is not happening at all.  So am not sure if it is related to method names, because the call is happening between two java components.

**Comment by zalym** [comment]
Hi Jim,

It was a sync issue!  :)

Thanks for your help

**Comment by jimlloyd** [comment]
@zalym cool, glad I could help.
