### ISSUE TITLE
Does every method of a class has both sync and async version

### ISSUE THREAD

**Issue by sgarggit** [joeferner/node-java#204]
Hi,
I am writing a node program to use JNDI bind and lookup mechanism. I am getting following error while calling bind method

"Method 'lookup' called without a callback did you mean to use the Sync version?"

This is how I am making a call 

ctxg.lookup ("jdbc/datasource");

However, when I called bind method I did not get such error. This is how bind is called

ctxg.bind ("jdbc/ConnPool",ods);

What could be the issue. Did anyone face such issue. Is there any documentation on how java methods should be called from Node.

Thanks,
Sachin

**Comment by jimlloyd** [comment]
See the README.md, specifically the section [Java Objects:Call Method](javaObjectCallMethod).

So to call the lookup method, you call call either sync method:

```
var result = ctxg.lookupSync("jdbc/datasource");
```

or the async method:

```
ctxg.lookup("jdbc/datasource", function(err, result) { ... });
```

**Comment by dasarindam** [comment]
another example ... property class can be written like this.



var ver = javaLangSystem.getPropertySync("java.version");
