### ISSUE TITLE
Event Emitters

### ISSUE THREAD

**Issue by zalym** [joeferner/node-java#205]
I have a java class that does a lot of the heavy lifting, and once done, it calls an Interface to notify of events.  From node, I write a java proxy for that interface to do work.  

Is there something like an Event Emitter that would use reflection and trigger events based on the methodNames and the arguments?

Cheers

**Comment by jimlloyd** [comment]
@zalym: I think the feature you're describing doesn't exist, though it would be cool if it did. In general, node-java is a great enabler of using Java from node.js applications, but it hasn't (yet?) resulted in an ecosystem of reusable modules.
