### ISSUE TITLE
document how to use node-java with existing maven project

### ISSUE THREAD

**Issue by david-gang** [joeferner/node-java#215]
Hi,

Do you think it would be helpful to have documentation of how to configure node-java with an existing project?

I would have been happy if the content of this thread would have been documented:
https://groups.google.com/d/topic/node-java/LA2tct18rqg/discussion

What do you think?

Thanks,
David

**Comment by joeferner** [comment]
Yes, that would be great. If you would like to write up a little section for the readme I'll be glad to include it.
