### ISSUE TITLE
To JSON of an ArrayList property

### ISSUE THREAD

**Issue by kismis** [joeferner/node-java#221]
Hi,

Thanks for this great lib.

So I have a method i.e. `createA();` returning a struct A with an ArrayList property: 

```java
public class A {
  public ArrayList<B> titles = new ArrayList<B>();
}
```

Where B is another class:

```java
public class B {
  public String title = "";
}
```

I call the `createA();` from the nodejs side, however, it can't return the correct conversion of ArrayList (the `titles` property); instead it is converted as an empty object `{}` (it supposed to be an `[{ title : 'a'}, ...]` ?). Am I missing something here?

I put some example here https://github.com/kismis/hello-node-java 

Thank you!

**Comment by kjvalencik** [comment]
@kismis, this is because there is auto-conversion of `ArrayList` to `Array`. Try calling `.toArraySync()` on the object. I.e.,

    console.log(a.toArraySync());

**Comment by kismis** [comment]
Ah yeah! Nice! Thank @kjvalencik !!! 

```js
console.log(a.titles.toArraySync());
```

saves my day! Thanks!
