### ISSUE TITLE
Doesn't work on OS X 10.11 El Capitan, but installs correctly

### ISSUE THREAD

**Issue by clns** [joeferner/node-java#223]
After installing OS X 10.11 Beta, calling java methods on the `java` object doesn't work anymore, and a popup opens saying "*This application requires the legacy Java SE 6 runtime which is 
unavailable for this version of OS X.*".

However node-java installs successfully, the only thing I noticed is this message:

```
2015-06-09 17:09:03.971 xcodebuild[7059:336822] [MT] PluginLoading: Required plug-in 
compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path 
'~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' 
not present in DVTPlugInCompatibilityUUIDs
```

I also checked `find-java-home` and it's finding the correct jdk:

```
$ node findJavaHome.js
/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
```

More details can be found in this [related question on stackoverflow](http://stackoverflow.com/questions/30733214/some-java-programs-not-working-on-os-x-10-11).

**Comment by jimlloyd** [comment]
I left a comment on stackoverflow, but here it is again:

Please try installing the runtime as discussed here: https://discussions.apple.com/thread/6604985.
Let's hope this installer still works with El Capitan.

**Comment by clns** [comment]
Unfortunately that didn't work. I first added the question on SO because I am not sure if the issue is related to (or can be fixed in) node-java, since I noticed the same error with PhpStorm. However I mostly care about node-java to work.

**Comment by clns** [comment]
A working solution can be found [here](https://github.com/joeferner/node-java/issues/90#issuecomment-45613235).

In short, Oracle's JDK doesn't advertise itself as supporting JNI, so even though node-java links to JAVA_HOME correctly, when the `JNI_CreateJavaVM` call is made the system sees that the linked JDK doesn't "support" JNI and switches to Java 6 instead.

To fix this I manually enabled JNI by editing 
`/Library/Java/JavaVirtualMachines/<version>.jdk/Contents/Info.plist` and adding `JNI` as an option in `JVMCapabilities`:
```xml
<key>JVMCapabilities</key>
<array>
    ...
    <string>JNI</string>
</array>
```

**Comment by junqdu** [comment]
@clns any idea why JDK doesn't advertise itself as supporting JNI?

**Comment by clns** [comment]
@junqdu No idea.
