### ISSUE TITLE
npm install java fails on EC2 AMI linux?

### ISSUE THREAD

**Issue by lmessinger** [joeferner/node-java#224]
Hi

I cant install on Amazon AMI. below is what I get. any ideas?

thanks very much!
Lior

[ec2-user@ip-172-30-0-36 server]$ npm install java
npm WARN package.json node-java@1.0.1 No repository field.
npm WARN package.json node-java@1.0.1 No README data
-
> java@0.5.4 install /home/ec2-user/OnTopIt-XL/server/node_modules/java
> node-gyp rebuild

[node-java] Error: not found: javac
gyp: Call to 'node findJavaHome.js' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.14.27-25.47.amzn1.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/OnTopIt-XL/server/node_modules/java
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! java@0.5.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.5.4 install script.
npm ERR! This is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.14.27-25.47.amzn1.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "java"
npm ERR! cwd /home/ec2-user/OnTopIt-XL/server
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
[ec2-user@ip-172-30-0-36 server]$

**Comment by jsdevel** [comment]
Looks like you need to install the jdk
```
Error: not found: javac
```

**Comment by lmessinger** [comment]
thanks. it is installed, I believe:
[ec2-user@ip-172-30-0-36 server]$ rpm -qa | grep openjdk
java-1.7.0-openjdk-1.7.0.79-2.5.5.1.59.amzn1.x86_64

am I right?

**Comment by lmessinger** [comment]
found it! need to install the dev package

I ran sudo yum install java-1.8.0-openjdk-devel, then the npm installed just fine.

**Comment by jsdevel** [comment]
glad you got it working!
