### ISSUE TITLE
Map parameter is always null

### ISSUE THREAD

**Issue by grd2345** [joeferner/node-java#225]
when i try to pass a json object as a parameter to my java class, the Map parameter in java is always null. What is the correct way to pass a Map parameter to get this to work?

**Comment by jimlloyd** [comment]
See #56. There currently is no automatic translations between javascript objects and Java Maps. You currently have to create a map (probably using java.newInstanceSync('java.util.HashMap')) and then copy the key,value pairs from the Javascript object to the Java map. @jsdevel linked to some code in #56 that you can probably use: https://github.com/jsdevel/webdriver-sync/blob/master/src/utils.js#L70

I'm closing this issue, follow-ups should be in #56.
