### ISSUE TITLE
nodemon does not restart server when callStaticMethodSync is used

### ISSUE THREAD

**Issue by dannyn-mirth** [joeferner/node-java#226]
I don't know if my issue is isolated in my environment, but I seem to be able to replicate the issue fine.

I'm using nodemon v1.3.7 to speed up my node.js development. The problem I'm running into is this line of code:
```javascript
    var java = require('java'),
    java.callStaticMethodSync("java.lang.ClassLoader","getSystemClassLoader");
```
For some reason that code above prevents nodemon from restarting the server when it detects changes in the project. I'm not sure if this is a nodemon issue or a node-java issue. If I comment that line of code above, nodemon restarts the server as normal.

What could be causing nodemon to hang when calling that code? 

I have completely isolated the issue. Meaning I created a node module with only the following:
```javascript
    // test_nodemon.js
    var java = require('java'),
    function test() {
        java.callStaticMethodSync("java.lang.ClassLoader","getSystemClassLoader");
    }

    module.exports = test;
```
And I was able to replicate the issue of nodemon not restarting because of the callStatisMethodSync.

Can someone shine some light on this?

**Comment by dannyn-mirth** [comment]
I found out that this is very likely a nodemon issue and not a node-java issue.

I tested using another library called node-supervisor, which essentially does the same thing as nodemon and node-supervisor restarts the nodejs server just fine.

**Comment by jimlloyd** [comment]
Almost certainly the problem is that nodemon doesn't deal well with the JVM creation & termination. The JVM is created lazily by the first call to one of the java functions such as `java.callStaticMethodSync()` or `java.import()`, so there is most likely nothing special about your use of `java.callStaticMethodSync()`.
