### ISSUE TITLE
Where java code which is called from node js ,will run? on JVM or V8 ?

### ISSUE THREAD

**Issue by mindfireon812** [joeferner/node-java#232]

**Comment by jimlloyd** [comment]
One process is created. The initialization sequence first initializes V8, and then uses JNI to create a JVM. All Java code runs within the JVM, but every call from Javascript to Java goes through some glue code, and in some cases some additional logic is run for convenience, e.g. conversion of primitive types (strings, numbers, booleans) between their Javascript and Java representations.
