### ISSUE TITLE
How to set application properties file path?

### ISSUE THREAD

**Issue by sunnyfrancis** [joeferner/node-java#236]
I need to set application properties (app.properties) path using node-java.

I've tried the same for log4j and it works.Here is the sample code:
java.callStaticMethodSync("org.apache.log4j.xml.DOMConfigurator", "configure", "./lib/Logging.xml");

Do we have something like above to set path for java application properties file?

**Comment by sunnyfrancis** [comment]
This issue is solved by providing a method in java (in a jar file that you are trying to consume) and invoke it from Node JS. Method job would be to load properties file in memory which can be picked up by the target code of java when its being executed

**Comment by frosas** [comment]
Haven't tried but this should work:

```js
var Properties = java.import('java.util.Properties');
var FileInputStream = java.import('java.io.FileInputStream');
var System = java.import('java.lang.System');

var properties = new Properties;
properties.load(new FileInputStream('app.properties'));
System.setProperties(properties);
```
