### ISSUE TITLE
electron rebuild issue

### ISSUE THREAD

**Issue by brant-hwang** [joeferner/node-java#237]
Hi ! Thanks for your contribution. 

First off, I executed node-java with & nwjs & node successfully following versions.

node-java : 0.5.4
node : 0.12.7
nwjs : 0.0.12

Second, I tried  to build up node-java with Electron.

Electron version : 0.30.3
Electron rebuild version : 0.2.5

My working steps is like,  

1) npm install electron-prebuilt & electron-rebuild
2) ./node_modules/.bin/electron-rebuild

But, the errors were occured as the title said:

```
1033 info build /Workspace/node-java-example/node_modules/java
1034 info preinstall java@0.5.4
1035 info linkStuff java@0.5.4
1036 silly linkStuff java@0.5.4 has /Workspace/node-java-example/node_modules as its parent node_modules
1037 verbose linkBins java@0.5.4
1038 verbose linkMans java@0.5.4
1039 verbose rebuildBundles java@0.5.4
1040 verbose rebuildBundles [ 'async', 'find-java-home', 'glob', 'lodash', 'nan' ]
1041 info install java@0.5.4
1042 verbose unsafe-perm in lifecycle true
1043 info java@0.5.4 Failed to exec install script
1044 verbose stack Error: java@0.5.4 install: `node-gyp rebuild`
1044 verbose stack Exit status 1
1044 verbose stack     at EventEmitter.<anonymous> (/Workspace/node-java-example/node_modules/electron-rebuild/node_modules/npm/lib/utils/lifecycle.js:214:16)
1044 verbose stack     at EventEmitter.emit (events.js:110:17)
1044 verbose stack     at ChildProcess.<anonymous> (/Workspace/node-java-example/node_modules/electron-rebuild/node_modules/npm/lib/utils/spawn.js:24:14)
1044 verbose stack     at ChildProcess.emit (events.js:110:17)
1044 verbose stack     at maybeClose (child_process.js:1015:16)
1044 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
1045 verbose pkgid java@0.5.4
1046 verbose cwd /Workspace/node-java-example/node_modules
1047 error Darwin 14.4.0
1048 error argv "node" "/Workspace/node-java-example/node_modules/electron-rebuild/node_modules/npm/bin/npm-cli.js" "rebuild" "--target=0.30.3" "--arch=x64"
1049 error node v0.12.7
1050 error npm  v2.13.4
1051 error code ELIFECYCLE
1052 error java@0.5.4 install: `node-gyp rebuild`
1052 error Exit status 1
1053 error Failed at the java@0.5.4 install script 'node-gyp rebuild'.
1053 error This is most likely a problem with the java package,
1053 error not with npm itself.
1053 error Tell the author that this fails on your system:
1053 error     node-gyp rebuild
1053 error You can get their info via:
1053 error     npm owner ls java
1053 error There is likely additional logging output above.
1054 verbose exit [ 1, true ]
```

Then, I had changed nodejs to iojs,
But the erros was occured as I attached again.

Can you test or check up to Electron?
Thanks.

**Comment by alienatorZ** [comment]
I am also having the same issue. 

It started when I added the node-java module to my elecron app and got 'module did not self register' error.

**Comment by thomasJang** [comment]
me too~! plz fix it

**Comment by SQLGate** [comment]
I'm such a problem. Please check it

**Comment by lrenard** [comment]
I have used the last commit from the branch upgrade-nan-to-2 and it seems to resolve the issue with electron.

**Comment by thomasJang** [comment]
:+1:

**Comment by alienatorZ** [comment]
I was able to successfully compile in latest Electron and Node.js 4.1 but upon running I get the error:

Uncaught Error: A dynamic link library (DLL) initialization routine failed.
C:\Users\Adam\Downloads\electron-v0.33.0-win32-x64\resources\app\node_modules\java\build\Release\nodejavabridge_bindings.node
Error: A dynamic link library (DLL) initialization routine failed.
C:\Users\Adam\Downloads\electron-v0.33.0-win32-x64\resources\app\node_modules\java\build\Release\nodejavabridge_bindings.node
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Adam\Downloads\electron-v0.33.0-win32-x64\resources\app\node_modules\java\lib\nodeJavaBridge.js:10:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by brant-hwang** [comment]
Thanks a lot. 
It works well!
