### ISSUE TITLE
Unable to use Java Maps in JavaScript

### ISSUE THREAD

**Issue by SamReha** [joeferner/node-java#243]
I've recently started working with this module and have been having trouble getting a Map<String, String> to convert into a JS object. To show off my issue, here is some sample code to help explain what I want to do, and what is actually happening.

My Java class:
```
import java.util.HashMap;
import java.util.Map;

public class DoStuffWithMaps {
    Map<String, String> testMap;
    public DoStuffWithMaps () {
        testMap = new HashMap<String, String>();
        testMap.put("Hello", "World");
    }
    public Map<String, String> getMap() {
        return testMap;
    }
}
```

And my Node app:
```
var java = require('java')

java.classpath.push(__dirname + '\\java\\do_stuff_with_maps.jar')
java.import('java.util.HashMap')
java.import('java.util.Map')

var DoStuffWithMaps = java.import('DoStuffWithMaps')
var doStuffWithMaps = new DoStuffWithMaps()
console.log(doStuffWithMaps.getMapSync())
```
DoStuffWithMaps has, of course, been exported as a jar file and stuck in a directory called /java/ alongside the node app itself.

I expect the output from running the node app to be:
```
{"Hello":"World"}
```

Instead, it is:
```
{}
```

Is there a reason to this? I am new to this tool, so I may be using it entirely incorrectly. Alternatively, are generic collections something that Node Java simply will not do?

**Comment by joeferner** [comment]
Node java currently doesn't convert maps to javascript maps.  Try calling toStringSync on the {}

**Comment by SamReha** [comment]
Thanks for the quick response, Joe! Calling toString() on the object from JS does indeed properly stringify the map - so it's clearly not an issue with the package, just me trying to use a feature that isn't there.

For now, I'll just serialize my maps as JSONs from within Java and pass them around as strings.

**Comment by jeremypng** [comment]
This is a similar problem. I'm trying to use a Java SDK from within node and it wants me to pass it a hashmap.

In Java the code looks like this
```java
        Customer customer = new Customer(
                DataElementUtils.convertDataMapToSet(
                    new HashMap<String, Object>() {{
                        put("Context_Work_Email", "***");
                        put("Context_First_Name", "***");
                        put("Context_Last_Name", "***");
                        put("Context_Company_Name", "***");
                        put("Context_Work_Phone", "***");
                    }}
                )
        );
        customer.setFieldsets(Arrays.asList("cisco.base.customer"));
        contextServiceClient.create(customer);
```

In JavaScript I get about this far and I'm stuck:

```javascript
    var Customer = java.import('com.cisco.thunderhead.customer.Customer');
    var HashMap = java.import('java.util.HashMap');
    var hashMap = new HashMap<----How do I build a <String, Object> map for this?
```

Any ideas?

**Comment by joeferner** [comment]
Java does not preserve generics at runtime so this should work.

```
var hashMap = new HashMap();
hashMap.putSync('a', 'b');
```
