### ISSUE TITLE
Multiple JVM instances

### ISSUE THREAD

**Issue by tristanz** [joeferner/node-java#245]
Is there any way to have multiple JVM instances? Basically `var java = require('java')()` rather than the currently singleton approach.  I have an application that needs to be able to have different class paths due to conflicting library versions.

**Comment by joeferner** [comment]
I don't believe JNI can create multiple JVMs. You may want to try a tool like jarjar (https://github.com/shevek/jarjar) to repackage the conflicting jars.

**Comment by jzakrzewski** [comment]
It's explicit somewhere in Oracle documentation (I have found it long ago when trying to spawn few instances) - there can be only one instance per process.

The normal approach to such conflicts is using different class loaders although I do not know if it's possible with node-java.
