### ISSUE TITLE
How to I get object that return from java 

### ISSUE THREAD

**Issue by juniorkid** [joeferner/node-java#246]
I want to get object that create in java program
I can try but it has problem:
Error: Error running instance method
java.lang.NullPointerException

How i can do it ?

Thank you.

**Comment by joeferner** [comment]
Can you provide more information. Possibly the Java code and JavaScript code.

**Comment by juniorkid** [comment]
I can solve this problem. This problem is caused by me.
Thank you for your commend and sorry for bad english.
