### ISSUE TITLE
Stuck threads on node.NodeDynamicProxyClass.callJs with multiple concurrent clients

### ISSUE THREAD

**Issue by bayareagreg** [joeferner/node-java#262]
My code executes just fine as long as I send I request at a time. When I have many  concurrent clients, I am seeing the server is stuck. When I do a thread dump I see this:

```
2015-10-02 22:31:26
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.40-b12 mixed mode):

"Attach Listener" #14 daemon prio=9 os_prio=0 tid=0x00007f14f8001000 nid=0x6041 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Thread-3" #13 prio=5 os_prio=0 tid=0x00007f14d4005800 nid=0x5fcc runnable [0x00007f14fe0e8000]
   java.lang.Thread.State: RUNNABLE
    at node.NodeDynamicProxyClass.callJs(Native Method)
    at node.NodeDynamicProxyClass.invoke(NodeDynamicProxyClass.java:34)
    at com.sun.proxy.$Proxy0.getUrl(Unknown Source)
    at RequestProcessor.processMessage(RequestProcessor.java:12)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)

"Thread-2" #12 prio=5 os_prio=0 tid=0x000000000405b800 nid=0x5fca runnable [0x00007f14ff0ea000]
   java.lang.Thread.State: RUNNABLE
    at node.NodeDynamicProxyClass.callJs(Native Method)
    at node.NodeDynamicProxyClass.invoke(NodeDynamicProxyClass.java:34)
    at com.sun.proxy.$Proxy1.send(Unknown Source)
    at RequestProcessor.processMessage(RequestProcessor.java:13)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)

"Thread-1" #11 prio=5 os_prio=0 tid=0x00007f14d4001000 nid=0x5fc9 runnable [0x00007f14ff8eb000]
   java.lang.Thread.State: RUNNABLE
    at node.NodeDynamicProxyClass.callJs(Native Method)
    at node.NodeDynamicProxyClass.invoke(NodeDynamicProxyClass.java:34)
    at com.sun.proxy.$Proxy1.send(Unknown Source)
    at RequestProcessor.processMessage(RequestProcessor.java:13)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)

"Thread-0" #10 prio=5 os_prio=0 tid=0x00007f14e0001000 nid=0x5fcb runnable [0x00007f14fe8e9000]
   java.lang.Thread.State: RUNNABLE
    at node.NodeDynamicProxyClass.callJs(Native Method)
    at node.NodeDynamicProxyClass.invoke(NodeDynamicProxyClass.java:34)
    at com.sun.proxy.$Proxy1.send(Unknown Source)
    at RequestProcessor.processMessage(RequestProcessor.java:13)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x0000000003fc6800 nid=0x5fa6 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread1" #8 daemon prio=9 os_prio=0 tid=0x0000000003f19800 nid=0x5fa5 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #7 daemon prio=9 os_prio=0 tid=0x0000000003f16800 nid=0x5fa4 waiting on condition [0x0000000000000000]
```

In other words, all threads seem to be stuck on
node.NodeDynamicProxyClass.callJs

the diagram is this:
node->java->node

on the java side the call to oracle.osblite.runtime.transports.http.InboundRequest.getUrl is invoked. 
on the javascript side (node.js) the code looks something like

```
function inboundRequestCallback(req, operation)
{
   return java.newProxy("oracle.osblite.runtime.transports.http.InboundRequestCallback",
   {
        getUrl: function()
        {
            console.log(">>>>>>> + getUrl")
            return req.url;
        },
        getBaseUrl: function()
        {
```

I never see the console message above
Any ideas what might be going on here?
Thanks in advance

**Comment by bayareagreg** [comment]
I sent a standalone reproducer to Joe in email. Not able to attach it here: it is a gzip file. Bleh
Instructions:
1) ant build
2) node test.js
3) ant run in separate window

should see stuck threads. I am running node v0.12.7

**Comment by joeferner** [comment]
I created a gist with all the necessary files here: https://gist.github.com/joeferner/d9afa409af3e19cd00d9

**Comment by joeferner** [comment]
Unfortunately I am unable to reproduce the error...

```
> node -v
v0.12.7
> java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
> uname -a
Linux jferner 4.2.2-1-ARCH #1 SMP PREEMPT Tue Sep 29 22:21:33 CEST 2015 x86_64 GNU/Linux
```

```
> node test.js 
Listening for transport dt_socket at address: 8453
>>>>
>>>> HTTP Server for running on port 7001. Hit Ctrl+C to shut down...
>>>>
>>>> + onInboundMessage readable
>>>> + onInboundMessage readable
>>>> + onInboundMessage readable
>>>> + onInboundMessage readable
>>>> + onInboundMessage readable
>>>> + onInboundMessage readable
>>>> + onInboundMessage readable
>>>> + onInboundMessage readable
>>>> + onInboundMessage readable
>>>> + onInboundMessage readable
>>>>>>> + getUrl
>>>>>>> + getUrl
>>>>>>> + getUrl
RequestProcessor: request URL is /
RequestProcessor: request URL is /
RequestProcessor: request URL is /
```

```
ant run
Buildfile: build.xml

run:
     [java] [ Thread-9][   0][http://localhost:7001/foo]+
     [java] [ Thread-0][   0][http://localhost:7001/foo]+
     [java] [ Thread-1][   0][http://localhost:7001/foo]+
     [java] [ Thread-2][   0][http://localhost:7001/foo]+
     [java] [ Thread-3][   0][http://localhost:7001/foo]+
     [java] [ Thread-4][   0][http://localhost:7001/foo]+
     [java] [ Thread-5][   0][http://localhost:7001/foo]+
     [java] [ Thread-6][   0][http://localhost:7001/foo]+
     [java] [ Thread-7][   0][http://localhost:7001/foo]+
     [java] [ Thread-8][   0][http://localhost:7001/foo]+
```

Can you give me more info about your setup (JDK version, OS).

**Comment by bayareagreg** [comment]
Away from computer now. In a couple of hours. Thanks

**Comment by bayareagreg** [comment]
Ok here it is

[gfichten@slc00fgh nodeJavaBug]$ node -v
v0.12.7

[gfichten@slc00fgh nodeJavaBug]$ java -version
java version "1.8.0_40-ea"
Java(TM) SE Runtime Environment (build 1.8.0_40-ea-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b12, mixed mode)

[gfichten@slc00fgh nodeJavaBug]$ uname -a
Linux slc00fgh 3.8.13-16.2.1.el6uek.x86_64 #1 SMP Thu Nov 7 17:01:44 PST
2013 x86_64 x86_64 x86_64 GNU/Linux

(I am basically running OEL6)

How do we proceed?
Thanks
Greg

**Comment by bayareagreg** [comment]
Joe,
2 things.
1) I took a look at your message again and I believe you did reproduce the
problem.
The client (the one doing 'ant run') needs to get a response 'hello world'
for each request on each thread. Your output shows it is not getting it.

Try to modify 'run' task in build.xml to use 1 message and 1 thread
 <arg line="http://localhost:7001/foo 1 1"/>
you will see what I mean. The request runs successfully to completion. You
should see this on the client

     [java] [ Thread-0][   0][http://localhost:7001/foo]+
     [java] [ Thread-0][   0]-[   83][83][200
OK][{Transfer-Encoding=[chunked], null=[HTTP/1.1 200 OK],
Connection=[keep-alive], Date=[Sat, 03 Oct 2015 21:50:15 GMT],
X-Powered-By=[Express]}]
     [java] Response is :
     [java] hello world

I believe your output proves your server is stuck just like mine.

Do a 'jps' and then 'jstack' to get the thread dump of the server - you
should see the stack similar to what I sent before.

2) I also tried
bash-4.1$ java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

and got the same result.


Let me know how it goes
Thanks

Greg

**Comment by bayareagreg** [comment]
Joe, any news?
Thanks

**Comment by joeferner** [comment]
I haven't had time to look at it. I'll let you know

On October 5, 2015 8:19:09 PM EDT, bayareagreg <notifications@github.com> wrote:
>Joe, any news?
>Thanks
>
>
>On Sat, Oct 3, 2015 at 2:51 PM, Greg Fichtenholtz
><bayareagreg@gmail.com>
>wrote:
>
>> Joe,
>> 2 things.
>> 1) I took a look at your message again and I believe you did
>reproduce the
>> problem.
>> The client (the one doing 'ant run') needs to get a response 'hello
>world'
>> for each request on each thread. Your output shows it is not getting
>it.
>>
>> Try to modify 'run' task in build.xml to use 1 message and 1 thread
>>  <arg line="http://localhost:7001/foo 1 1"/>
>> you will see what I mean. The request runs successfully to
>completion. You
>> should see this on the client
>>
>>      [java] [ Thread-0][   0][http://localhost:7001/foo]+
>> <http://localhost:7001/foo%5D+>
>>      [java] [ Thread-0][   0]-[   83][83][200
>> OK][{Transfer-Encoding=[chunked], null=[HTTP/1.1 200 OK],
>> Connection=[keep-alive], Date=[Sat, 03 Oct 2015 21:50:15 GMT],
>> X-Powered-By=[Express]}]
>>      [java] Response is :
>>      [java] hello world
>>
>> I believe your output proves your server is stuck just like mine.
>>
>> Do a 'jps' and then 'jstack' to get the thread dump of the server -
>you
>> should see the stack similar to what I sent before.
>>
>> 2) I also tried
>> bash-4.1$ java -version
>> java version "1.8.0_51"
>> Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
>> Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
>>
>> and got the same result.
>>
>>
>> Let me know how it goes
>> Thanks
>>
>> Greg
>>
>> On Sat, Oct 3, 2015 at 1:15 PM, Greg Fichtenholtz
><bayareagreg@gmail.com>
>> wrote:
>>
>>> Ok here it is
>>>
>>> [gfichten@slc00fgh nodeJavaBug]$ node -v
>>> v0.12.7
>>>
>>> [gfichten@slc00fgh nodeJavaBug]$ java -version
>>> java version "1.8.0_40-ea"
>>> Java(TM) SE Runtime Environment (build 1.8.0_40-ea-b08)
>>> Java HotSpot(TM) 64-Bit Server VM (build 25.40-b12, mixed mode)
>>>
>>> [gfichten@slc00fgh nodeJavaBug]$ uname -a
>>> Linux slc00fgh 3.8.13-16.2.1.el6uek.x86_64 #1 SMP Thu Nov 7 17:01:44
>PST
>>> 2013 x86_64 x86_64 x86_64 GNU/Linux
>>>
>>> (I am basically running OEL6)
>>>
>>> How do we proceed?
>>> Thanks
>>> Greg
>>>
>>>
>>> On Sat, Oct 3, 2015 at 11:35 AM, Joe Ferner
><notifications@github.com>
>>> wrote:
>>>
>>>> Unfortunately I am unable to reproduce the error...
>>>>
>>>> > node -v
>>>> v0.12.7
>>>> > java -version
>>>> java version "1.8.0_45"
>>>> Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
>>>> Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
>>>> > uname -a
>>>> Linux jferner 4.2.2-1-ARCH #1 SMP PREEMPT Tue Sep 29 22:21:33 CEST
>2015 x86_64 GNU/Linux
>>>>
>>>> > node test.js
>>>> Listening for transport dt_socket at address: 8453
>>>> >>>>
>>>> >>>> HTTP Server for running on port 7001. Hit Ctrl+C to shut
>down...
>>>> >>>>
>>>> >>>> + onInboundMessage readable
>>>> >>>> + onInboundMessage readable
>>>> >>>> + onInboundMessage readable
>>>> >>>> + onInboundMessage readable
>>>> >>>> + onInboundMessage readable
>>>> >>>> + onInboundMessage readable
>>>> >>>> + onInboundMessage readable
>>>> >>>> + onInboundMessage readable
>>>> >>>> + onInboundMessage readable
>>>> >>>> + onInboundMessage readable
>>>> >>>>>>> + getUrl
>>>> >>>>>>> + getUrl
>>>> >>>>>>> + getUrl
>>>> RequestProcessor: request URL is /
>>>> RequestProcessor: request URL is /
>>>> RequestProcessor: request URL is /
>>>>
>>>> ant run
>>>> Buildfile: build.xml
>>>>
>>>> run:
>>>>      [java] [ Thread-9][   0][http://localhost:7001/foo]+
><http://localhost:7001/foo%5D+>
>>>>      [java] [ Thread-0][   0][http://localhost:7001/foo]+
><http://localhost:7001/foo%5D+>
>>>>      [java] [ Thread-1][   0][http://localhost:7001/foo]+
><http://localhost:7001/foo%5D+>
>>>>      [java] [ Thread-2][   0][http://localhost:7001/foo]+
><http://localhost:7001/foo%5D+>
>>>>      [java] [ Thread-3][   0][http://localhost:7001/foo]+
><http://localhost:7001/foo%5D+>
>>>>      [java] [ Thread-4][   0][http://localhost:7001/foo]+
><http://localhost:7001/foo%5D+>
>>>>      [java] [ Thread-5][   0][http://localhost:7001/foo]+
><http://localhost:7001/foo%5D+>
>>>>      [java] [ Thread-6][   0][http://localhost:7001/foo]+
><http://localhost:7001/foo%5D+>
>>>>      [java] [ Thread-7][   0][http://localhost:7001/foo]+
><http://localhost:7001/foo%5D+>
>>>>      [java] [ Thread-8][   0][http://localhost:7001/foo]+
><http://localhost:7001/foo%5D+>
>>>>
>>>> Can you give me more info about your setup (JDK version, OS).
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>>
><https://github.com/joeferner/node-java/issues/262#issuecomment-145276090>
>>>> .
>>>>
>>>
>>>
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/joeferner/node-java/issues/262#issuecomment-145704923

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bayareagreg** [comment]
Just FWIW, a little bit of debugging shows that

    uv_queue_work(uv_default_loop(), req, EIO_CallJs,
(uv_after_work_cb)EIO_AfterCallJs);

gets called but EIO_AfterCallJs never does

so it gets stuck here

    while(!dynamicProxyData->done) {
      my_sleep(100);
    }

regardless of actual problem, probly not a great idea to have a "sleep"
loop without any kind of timeout

**Comment by jkstrick** [comment]
I am able to reproduce this error with the following code.  Also, I have a pull request to fix it. (https://github.com/joeferner/node-java/pull/496)

test_concurrency.js:
```
var java = require("java");
java.classpath.push('.');

var counter = 0;

var supplier = java.newProxy('java.util.function.DoubleSupplier', {
    'getAsDouble': function() { return java.newDouble(counter++); }
});

java.callStaticMethod('ThreadSpammer', 'runMany', supplier, 10);

setTimeout(process.exit, 5000);
```

ThreadSpammer.java:
```
import java.lang.Thread;
import java.lang.Runnable;
import java.util.function.DoubleSupplier;

public class ThreadSpammer
{
    public static void runMany(DoubleSupplier s1, int numThreads)
    {
        for(int i = 0; i < numThreads; i++) {
            Thread t1 = new Thread(new Runnable() {
                @Override
                public void run() {
                    System.out.println(s1.getAsDouble());
                }
            });

            t1.start();
        }
    }
}
```

When run without the fix, you see something like this:
```
$ node test-concurrency.js 
Exception in thread "Thread-2" java.lang.NullPointerException
        at com.sun.proxy.$Proxy0.getAsDouble(Unknown Source)
        at ThreadSpammer$1.run(ThreadSpammer.java:13)
        at java.lang.Thread.run(Thread.java:748)
2.0
Exception in thread "Thread-3" java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.Double
        at com.sun.proxy.$Proxy0.getAsDouble(Unknown Source)
        at ThreadSpammer$1.run(ThreadSpammer.java:13)
        at java.lang.Thread.run(Thread.java:748)
3.0
5.0
Exception in thread "Thread-6" java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.Double
        at com.sun.proxy.$Proxy0.getAsDouble(Unknown Source)
        at ThreadSpammer$1.run(ThreadSpammer.java:13)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-7" java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.Double
        at com.sun.proxy.$Proxy0.getAsDouble(Unknown Source)
        at ThreadSpammer$1.run(ThreadSpammer.java:13)
        at java.lang.Thread.run(Thread.java:748)
7.0
8.0
9.0
```

With the fix, you see this:
```
$ node test-concurrency.js 
0.0
8.0
7.0
6.0
5.0
4.0
2.0
1.0
9.0
3.0
```

**Comment by heimmen** [comment]
@joeferner I saw an UT error after downloading the latest code.

`× Java - Call Ambiguous Method - methodAmbiguous (sync) - double passed to int`
