### ISSUE TITLE
"Could not find method" when using no Promise suffix (base name)

### ISSUE THREAD

**Issue by rossj** [joeferner/node-java#266]
Hi There. I'm running into a small issue with the `asyncOptions` object when trying to have base name methods be the promisified versions.

Setting `promiseSuffix = "P"` like this works:
```javascript
let Promise = require('bluebird');
let java = require('java');

java.asyncOptions = {
  asyncSuffix: undefined,
  syncSuffix: "",
  promiseSuffix: "P",
  promisify: Promise.promisify
};

let integer = java.import('java.lang.Integer');
integer.parseIntP("1").then(...);
```

But this does not:

```javascript
let Promise = require('bluebird');
let java = require('java');

java.asyncOptions = {
  asyncSuffix: undefined,
  syncSuffix: "S",
  promiseSuffix: "",
  promisify: Promise.promisify
};

let integer = java.import('java.lang.Integer');
integer.parseInt("1").then(...);
```

The above code results in
````
Could not find method "parseInt(java.lang.String, (null))" on class "class java.lang.Integer"
````

For now, the obvious workaround is to use a suffix for promisified methods.

**Comment by jimlloyd** [comment]
See the section of the README titled [Notes](https://github.com/joeferner/node-java#notes), where it says:

* If you provide asyncOptions.promisify then you must provide a non-empty string for asyncOptions.promiseSuffix.
* Either (but not both) asyncSuffix or syncSuffix can be the empty string. If you want the defacto standard behavior for no suffix on async methods, you must provide an empty string for asyncSuffix.

I don't remember now the exact reason why it was difficult to support letting the promise suffix be the empty string, but I did initially try to support it and decided against it.

**Comment by rossj** [comment]
Sorry, I somehow missed the notes. I guess it's not a bug if it's documented.
