### ISSUE TITLE
q.denodeify

### ISSUE THREAD

**Issue by mlucool** [joeferner/node-java#267]
Hi,

Q.denodeify does not work in promisify. Using the example in the documention and changing: promisify: require("when/node").lift to   promisify: require("q").denodeify fails with the following:

node: ../node_modules/nan/nan_object_wrap.h:33: static T* Nan::ObjectWrap::Unwrap(v8::Local<v8::Object>) [with T = JavaObject]: Assertion `object->InternalFieldCount() > 0' failed.

Any suggestions?

Thanks,
Marc

**Comment by jimlloyd** [comment]
See the function `promisifyQ` in the file [testHelpers.js](https://github.com/joeferner/node-java/blob/master/testHelpers.js).

**Comment by mlucool** [comment]
Thanks!
