### ISSUE TITLE
Unload to load a java class from a jar file

### ISSUE THREAD

**Issue by panbhatt** [joeferner/node-java#273]
Hi Team,
I am using Java 8 and node-java module. and Trying to load a simple java class in the javascript file, however I am unable to do so. 
Here is the example and with output.
JS
var java = require('java') ;
var mvn = require('node-java-maven');

var String = java.import('java.lang.String');

var name = new String("Pankaj Bhatt") ;

console.log(JSON.stringify(name.toString() ));

mvn(function(err, mvnResults) {
  if (err) {
    return console.error('could not resolve maven dependencies', err);
  }
  mvnResults.classpath.forEach(function(c) {
    console.log('adding ' + c + ' to classpath');
    java.classpath.push(c);
  });

var path = require('path');
var fs = require('fs');
java.classpath.push(path.join(__dirname, "lib/SOS-1.0-SNAPSHOT.jar"));

  console.log("COMING HERE  ", java.classpath) ;

  
  var TestSoundsAndLeds = java.import('org.apache.commons.lang3.BooleanUtils');
  ;

});

OUTPUT
resolving parent: org.apache.commons:commons-parent:32
resolving parent: org.apache:apache:13
resolving parent: org.apache:apache:13
adding D:\Users\PBhatt\.m2\repository\org\usb4java\usb4java\1.2.0\usb4java-1.2.0
.jar to classpath
adding D:\Users\PBhatt\.m2\repository\org\usb4java\usb4java-javax\1.2.0\usb4java
-javax-1.2.0.jar to classpath
adding D:\Users\PBhatt\.m2\repository\org\usb4java\libusb4java\1.2.0\libusb4java
-1.2.0.jar to classpath
adding D:\Users\PBhatt\.m2\repository\org\apache\commons\commons-lang3\3.2.1\com
mons-lang3-3.2.1.jar to classpath
adding D:\Users\PBhatt\.m2\repository\javax\usb\usb-api\1.0.2\usb-api-1.0.2.jar
to classpath
COMING HERE   [ 'D:\\Temp\\SOS\\node_modules\\java\\commons-lang3-node-java.jar'
,
  'D:\\Temp\\SOS\\node_modules\\java\\src-java',
  'D:\\Users\\PBhatt\\.m2\\repository\\org\\usb4java\\usb4java\\1.2.0\\usb4java-
1.2.0.jar',
  'D:\\Users\\PBhatt\\.m2\\repository\\org\\usb4java\\usb4java-javax\\1.2.0\\usb
4java-javax-1.2.0.jar',
  'D:\\Users\\PBhatt\\.m2\\repository\\org\\usb4java\\libusb4java\\1.2.0\\libusb
4java-1.2.0.jar',
  'D:\\Users\\PBhatt\\.m2\\repository\\org\\apache\\commons\\commons-lang3\\3.2.
1\\commons-lang3-3.2.1.jar',
  'D:\\Users\\PBhatt\\.m2\\repository\\javax\\usb\\usb-api\\1.0.2\\usb-api-1.0.2
.jar',
  'D:\\Temp\\SOS\\lib\\SOS-1.0-SNAPSHOT.jar',
  pushDir: [Function] ]
D:\Temp\SOS\node_modules\java\lib\nodeJavaBridge.js:207
  var clazz = java.findClassSync(name); // TODO: change to Class.forName when
                   ^
Error: Could not create class org.apache.commons.lang3.BooleanUtils
java.lang.NoClassDefFoundError: org/apache/commons/lang3/BooleanUtils
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.BooleanUti
ls
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

    at Error (native)
    at Java.java.import (D:\Temp\SOS\node_modules\java\lib\nodeJavaBridge.js:207
:20)
    at D:\Temp\SOS\nodejava.js:29:38
    at Object.complete [as drain] (D:\Temp\SOS\node_modules\node-java-maven\inde
x.js:75:12)
    at next (D:\Temp\SOS\node_modules\node-java-maven\node_modules\async\lib\asy
nc.js:801:31)
    at D:\Temp\SOS\node_modules\node-java-maven\node_modules\async\lib\async.js:
32:16
    at D:\Temp\SOS\node_modules\node-java-maven\index.js:115:14
    at null.<anonymous> (D:\Temp\SOS\node_modules\node-java-maven\lib\dependency
.js:123:14)
    at wrapper (timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)

**Comment by joeferner** [comment]
Try moving `var String = java.import('java.lang.String');` line. All classpath operations must occur before using java APIs. Once the first java API is called the JVM is created and the classpath cannot be modified.

**Comment by joeferner** [comment]
Out of curiosity are you trying to control a Siren of Shame with node? If so you may want to look at: https://github.com/AutomatedArchitecture/node-sos-device.

**Comment by panbhatt** [comment]
Thanks. Yes . I think I am able to load it now. working ahead. 
Yes we are working on it. Since it is hard for us to make it work under node 12 because of the way bindings are created only for node 10, i decided to give this a shot.

**Comment by panbhatt** [comment]
Thanks. It worked like a charm. Now i m able to invoke my functions, Hence closing the issue. 
Thanks for the awesome project.

**Comment by joeferner** [comment]
I started a branch to get device-sos to work under Node 4 here: https://github.com/AutomatedArchitecture/node-sos-device/tree/switch-to-nan

I've already had success on Linux now I'm waiting for @lprichar to test it on windows before I merge and up the version.
