### ISSUE TITLE
Assertion failure when calling a method in async mode under Meteor

### ISSUE THREAD

**Issue by mhlmhl** [joeferner/node-java#277]
I am trying to use node-java in the Meteor environment on a Windows 8.1 64-bit system.  I have no problem new'ing a simple Java class and then invoking a method on the class via a synchronous call.  But when I call the method via an asynchronous call, I get an assertion failure in nodejavabridge_bindings.node at line 171, with the detail "Expression: !env->ExceptionCheck()".

Meteor installed a 32-bit version of Node, so I have installed a 32-bit version of Oracle Java.  "java -version" says:

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

Here's the server-only JS code that I am testing in Meteor:

Meteor.startup(function () {
try {

```
var java=Npm.require("java");
var javaCodePath=Meteor.rootPath + "\\assets\\app\\java\\";
java.classpath.push(javaCodePath);
java.classpath.push("c:\\Program Files (x86)\\Java\\jdk1.8.0_65\\lib");
java.classpath.push("commons-lang3-3.1.jar");
    java.classpath.push("commons-io.jar");
test = java.newInstanceSync("Test");
var result = test.doubleIntSync(13);
console.log("result=" + result);
java.callMethod(test, "doubleInt", 11, function(err, result) {
    console.log("reached callback");
    if (err) {console.log(err); return;}
    console.log("not an error");
    console.log(result);
});
```

} catch (e) {
    console.log("java setup error: " + e);
}
});

The "test = java.newInstanceSync("Test");" line works fine, returning the result I expect.  The assertion error fails on the "java.callMethod(test, "doubleInt", 11, function(err, result)" call and the callback function is not being called.

**Comment by joeferner** [comment]
Can you try

```
test.doubleInt(11.0, function(err, result) {});
```

**Comment by mhlmhl** [comment]
Same result.  See the screen image, below.

 

On a possibly-related point: I get “Exited with code: -1073741819” under circumstances that I don’t understand.  In particular, I need to call my Java code from within a Meteor callback.  If I do a synchronous call to the method during startup, then the (also synchronous) call in the callback works fine.  But if I comment-out the synchronous call (at line 12 in the attached java-trial-server.js) then the callback call fails with this exit.  Why would doing an initial call make the later call work?

 

I’ve attached both the .js that does the calls and my test Java code.  (I changed the call signature to receive a double argument and return a double result to eliminate mismatched types as a possible source of the problem.)


Thanks for your time.

 

 



 

 

Mark

**Comment by mhlmhl** [comment]
I'm closing this because I gave up on using node-java in this way.
