### ISSUE TITLE
Unable to pass a class back to java

### ISSUE THREAD

**Issue by madshall** [joeferner/node-java#278]
In my javascript(node 5.0.0) app I have imported an abstract java class A and extended it with a new child class B (class B extends A). Then I need to call a static method of another class C and pass my class B(not an instance, but something like B.class in java) as an argument. Playing with other parameters I found out that it's being taken as `(null)` and that's why I'm getting `java.lang.NullPointerException`. 

Support for interfaces exists, but I've not found anything similar for abstract classes.

**Comment by madshall** [comment]
Coming up with more details. So in my javascript code I do

```
var A = java.import("com.bom.mom.AbstractClassA");

class B extends A{
}

var test = new B(); //<== throws an exception java.lang.InstantiationException
```

So it looks like extending the abstract class in javascript makes the child class being an abstract too.

**Comment by joeferner** [comment]
I'm not sure if mixing language level classes like that will ever work. They are fundamentally different things.

**Comment by madshall** [comment]
I see and I'd love to extend the abstract class via java API instead as this is obviously the right way to do that, but is it supported? There is a possibility to proxy an interface, but I've not found anything regarding extending the class.

**Comment by joeferner** [comment]
Not really you could use delegation to pull it off.

Java

```java
public abstract class Animal {
  public abstract void makeNoise();
}

public interface AnimalDelegate {
  void makeNoise();
}

public class DelegatingAnimal {
  private AnimalDelegate animalDelegate;

  public DelegatingAnimal(AnimalDelegate animalDelegate) {
    this.animalDelegate = animalDelegate;
  }

  public void makeNoise() {
    animalDelegate.makeNoise();
  }
}
```

JavaScript

```javascript
var dog = new DelegatingAnimal(java.newProxy('AnimalDelegate', {
  makeNoise: function () {
    console.log("bark");
  }
}));

dog.makeNoise();

```
