### ISSUE TITLE
Is there a way to programmatically shutdown the java instance?

### ISSUE THREAD

**Issue by tobilg** [joeferner/node-java#279]
I use `node-java` similar to wha tis described at https://www.npmjs.com/package/java#using-node-java-in-existing-maven-projects

So, if I do a 

````

var javaInit = require('./javaInit');
var java = javaInit.getJavaInstance();
```

is there a way to "destroy" the `java` variable? In my application, it seems that I can't free the resources by just shutting down the Java application I launched...

**Comment by joeferner** [comment]
Looks like it might be possible via [DestroyJavaVM](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html#DestroyJavaVM) but that is not currently exposed

**Comment by tobilg** [comment]
Thanks for the fast answer. By *not currently exposed* you mean in `node-java`? If so, can this be implemented possibly?

**Comment by joeferner** [comment]
Should be easy to implement. Testing will be the hard part. Would you want the option to restart the JVM again?

**Comment by tobilg** [comment]
I'd prefer a clean shutdown of the JVM, so that the Node GC can free the resources. In my tests it was always the case that the Node processes memory was not freed after shutting down the Java process (I'm running Spark contexts via `node-java`)...

**Comment by narendra-agashe** [comment]
@tobilg did you find any solution to your issue..? I believe, I am running into similar problem.

**Comment by tobilg** [comment]
I worked around this by running the the process which launches the JVM as a worker process via the built-in cluster module. But this might not fit every use case. 

See

* https://nodejs.org/api/cluster.html#cluster_class_worker

**Comment by narendra-agashe** [comment]
Thanks @tobilg 
I am calling a JAR from my NodeJS Express Route, now thinking how to fit it as worker process.

**Comment by tobilg** [comment]
That's exactly how I use it too. You can use the inter-process messaging between the master process and the worker(s)...

**Comment by narendra-agashe** [comment]
Okay... That's great..
if it is feasible would you be able to give me some pointers, code sample..?

**Comment by tobilg** [comment]
Unfortunately I'm not in the office, so I can't give you some sample code right away. Basically I used the code from the Node.js docs. 

Start the worker on application start, and then use the *process.on('message')* listener on the worker to receive the tasks, and *worker.send()* from the master process to send the workload.

**Comment by narendra-agashe** [comment]
Okay.. Thanks a lot @tobilg .. :+1: 
even these clues would be helpful.. :+1:  let me give it a try..hopefully i will chase it down.

Right now i see that node process calls jar file successfully, jar file does its processing but then node process never releases memory acquired by the java and when i see that node process is swollen to 1 Gb on PM2 console, it looks super scary.

**Comment by narendra-agashe** [comment]
@tobilg were you doing something similar to this..? 
https://github.com/joeferner/node-java/issues/293
