### ISSUE TITLE
Another problem with java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by erobwen** [joeferner/node-java#281]
I am having problems with the class finder.

![image](https://cloud.githubusercontent.com/assets/7721859/11317858/ba87a7a2-903d-11e5-8ace-d53301776e23.png)

Here is my code: 

    var java = require("java");
    
    var path = require('path');
    var fs = require('fs');
    console.log(path.join(__dirname, "liquidNeo4JInterface.jar"));
    console.log('jar exists: ' + fs.existsSync(path.resolve(__dirname, "liquidNeo4JInterface.jar")));
    java.classpath.push(path.resolve(__dirname, "liquidNeo4JInterface.jar"));
    
    console.log(java.callStaticMethodSync('liquid.LiquidNeo4JInterface', 'getNode', 80));

Any ideas of how I could solve this problem? Right now I am out of ideas.

**Comment by erobwen** [comment]
Hmm... wait a minute, maybe I did not just get all things included in my Jar file? I thought the whole project got built into the Jar file, but perhaps library jar files are excluded?

**Comment by joeferner** [comment]
You can try https://github.com/joeferner/node-java-maven to get all the dependencies setup.
