### ISSUE TITLE
Creating instance of inner class

### ISSUE THREAD

**Issue by CrazzyCodeMonkey** [joeferner/node-java#287]
I am working with a large defined java library, and ran across a class with an inner class, that take 1 string parameter.

I tried just creating an instance of that object, and got this (Level is an inner class of Logger)

```
Level = java.newInstanceSync("com.acme.logger.Logger.Level",sLevel);
             ^

Error: Could not create class com.acme.logger.Logger.Level
java.lang.NoClassDefFoundError: com/acme/logger/Logger/Level
```

But if I import the class, and try to create it from there, 
```
Logger = java.import("com.acme.logger.Logger");
Level = Logger.Level(sLevel);
```
I get this

```
/nodecpp/jCommons/node_modules/java/lib/nodeJavaBridge.js:213
    return java.newInstanceSync.apply(java, args);
                                ^

Error: Could not find method "com.acme.logger.Logger$Level(java.lang.String)" on class "class com.acme.logger.Logger$Level". No methods with that name.
```

Does node-java support creating an inner class?

**Comment by unitive-jim** [comment]
The name of the inner class is `com.acme.logger.Logger$Level`, so you should try `Level = java.newInstanceSync("com.acme.logger.Logger.Level",sLevel);`. But the second error makes it look like that too will fail. Are the inner class and the constructor you want public?

**Comment by CrazzyCodeMonkey** [comment]
Thank you for input, my Java developer showed me a different way to get the object I was needing.
