### ISSUE TITLE
Question: Easy way to launch a new Thread, and let code run within this Thread

### ISSUE THREAD

**Issue by tobilg** [joeferner/node-java#290]
I saw what's documented for https://github.com/joeferner/node-java#javaNewProxy but I'm unsure how I can manually start a new Thread and make sure the code I pass gets executed below this Thread and not the global one.

**Background:**

I'm trying to run Spark job below one context in parallel. As the [Spark docs](http://spark.apache.org/docs/latest/job-scheduling.html#scheduling-within-an-application) state:

> multiple parallel jobs can run simultaneously if they were submitted from separate threads

I can run sequential jobs with my current code, but it fails when I want to run things in parallel.

**Comment by tobilg** [comment]
Can someone give me a hint?

**Comment by joeferner** [comment]
JavaScript code will always execute in the main thread. If you want to execute code in a separate thread it will need to be Java code. We should probably choose a different proxy example.

**Comment by tobilg** [comment]
Thanks for the feedback... Just that I understand correctly, the only way would be to create a new JAR file which launches the threads? If so, I'll need to call the methods/interfaces from Node, will this have an impact regarding *how* those need to be called to make sure that there's a new JVM thread launched?

Asked differently, would it be possible to give an example on how to create a new thread with `node-java`? I'm referring to

> If you want to execute code in a separate thread it will need to be Java code

which is not really clear too me I have to admit. 

Thanks again for your time and patience.

**Comment by joeferner** [comment]
You could do something like this

```java
public class MyJavaClass {
  public static void startThread() {
    Thread t = new Thread(...);
    t.start();
  }
}
```

```javascript
var MyJavaClass = java.import('MyJavaClass');
MyJavaClass.startThreadSync();
```

**Comment by tobilg** [comment]
Thanks, I see... I guess it will be hard then if I want the new thread to be able to access the Spark context which is instantiated via `node-java`? I.e. I need the new thread to be able to execute some code within the already started context/JVM, which I doubt is then possible.

**Comment by tobilg** [comment]
Sorry, another question (I'm a Java noob): Is there another way to implement inferfaces than with `newProxy()`?

**Comment by joeferner** [comment]
No in Javascript. I would recommend not using newProxy unless you really need to. I think it complicates the code and complicates the interaction between Java and Javascript.
