### ISSUE TITLE
Perfomance overhead

### ISSUE THREAD

**Issue by MathieuLoutre** [joeferner/node-java#316]
Hi there!

This looks exactly like what I need for my project. Has anyone done any performance test/benchmark ]to know if using this adds a seizable overhead to the Java execution? I'd like to use the Java part to do some heavy calculations with an external library (only available in Java) but build that into a Node.js web server.

Is there anything I should be aware of? Any tips on configuration, etc.?

Thanks for the hard work.

**Comment by joeferner** [comment]
There is definitely an overhead with using this bridge. It really depends on the situation and what type of objects are being crossed over. If you happen to find any slow spots let me know and I might be able to work on optimizing those areas.
