### ISSUE TITLE
Unable to install node-java module in Linux 6.x 

### ISSUE THREAD

**Issue by talasila66** [joeferner/node-java#318]
My Linux Server details are

Linux 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Dec 13 06:58:20 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

Red Hat Enterprise Linux Server release 6.5 (Santiago)

My jdk version is jdk1.7.0_51

When I tried to intsall using command npm install java I am getting the below errors

276919 error Linux 2.6.32-431.3.1.el6.x86_64
276920 error argv "/opt/node-v0.12.7-linux-x64/bin/node" "/opt/node-v0.12.7-linux-x64/bin/npm" "install"
276921 error node v0.12.7
276922 error npm  v2.11.3
276923 error code ELIFECYCLE
276924 error java@0.6.1 install: `node-gyp rebuild`
276924 error Exit status 1
276925 error Failed at the java@0.6.1 install script 'node-gyp rebuild'.
276925 error This is most likely a problem with the java package,
276925 error not with npm itself.
276925 error Tell the author that this fails on your system:
276925 error     node-gyp rebuild
276925 error You can get their info via:
276925 error     npm owner ls java
276925 error There is likely additional logging output above.
276926 verbose exit [ 1, true ]
276927 verbose unbuild node_modules/java
276928 info preuninstall java@0.6.1
276929 info uninstall java@0.6.1
276930 verbose unbuild rmStuff java@0.6.1 from /scratch/talasila66/git_wa/Test/nodeapp1/node_modules
276931 info postuninstall java@0.6.1
276932 silly gentlyRm /scratch/talasila66/git_wa/Test/nodeapp1/node_modules/java is being purged from base /scratch/talasila66/git_wa/Test/nodeapp1
276933 verbose gentlyRm don't care about contents; nuking /scratch/talasila66/git_wa/Test/nodeapp1/node_modules/java
276934 silly vacuum-fs purging /scratch/talasila66/git_wa/Test/nodeapp1/node_modules/java
276935 silly vacuum-fs quitting because other entries in /scratch/talasila66/git_wa/Test/nodeapp1/node_modules

Can you please help with the above issue?

**Comment by Anthonyzou** [comment]
Getting this issue on mac on node 6.0

    In file included from ../src/java.cpp:1:
    In file included from ../src/java.h:9:
    ../../nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
          v8::Isolate::GCEpilogueCallback callback
          ~~~~~~~~~~~~~^
    ../../nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
          v8::Isolate::GCEpilogueCallback callback) {
          ~~~~~~~~~~~~~^
    ../../nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
          v8::Isolate::GCPrologueCallback callback
          ~~~~~~~~~~~~~^
    ../../nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
          v8::Isolate::GCPrologueCallback callback) {
          ~~~~~~~~~~~~~^

**Comment by CraZySacX** [comment]
@Anthonyzou node-java won't work on node 6 until the nan dependency is updated.

**Comment by joeferner** [comment]
I've started a branch to support node 6 here: https://github.com/joeferner/node-java/tree/node-6

But, I'm currently hung up on this issue: https://github.com/nodejs/nan/issues/565

**Comment by joeferner** [comment]
@talasila66 Can you run `npm install --verbose` and grab that output

**Comment by joeferner** [comment]
@Anthonyzou can you try with the latest v0.7.0 version of node-java. I upgraded the Nan dependency and it works on my machine (Arch Linux) with Node v6

**Comment by Anthonyzou** [comment]
Yeah it's working now with node 6.0 on Mac

**Comment by DeChrish** [comment]
@Anthonyzou 
node 6.0 cannot be installed in linux box
