### ISSUE TITLE
Hi , I always got this error, but which module does not match ?

### ISSUE THREAD

**Issue by dawei101** [joeferner/node-java#319]
![image](https://cloud.githubusercontent.com/assets/2274609/14911364/81f207e4-0e27-11e6-8920-12ebeca8b6dd.png)

**Comment by joeferner** [comment]
Are you trying to use node-java in a browser?

**Comment by dawei101** [comment]
I see what happen now.
I was using node webkit to run a desktop app, if import java module, the *.node file should be rebuild by [nw-gyp](https://github.com/nwjs/nw-gyp)

thanks @joeferner
