### ISSUE TITLE
Error: Library is not initialized on the current thread.

### ISSUE THREAD

**Issue by xuezhma** [joeferner/node-java#323]
Hi,
I'm getting an error initializing a library. My code is:
```
var java = require('java');
var path = require('path');
java.classpath.push(path.join(__dirname, "APDFL10.1.0P5a/Java/com.datalogics.PDFL.jar"));

var Library =  java.import("com.datalogics.PDFL.Library");
var lib = new Library();
```
Full Error:
```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: The PDF Library is not initialized on the current thread.
```

Any idea why?

**Comment by joeferner** [comment]
Not really. The code above should all be running in the main node thread. If you had a call to the library that was causing the issue I would have suggested trying Sync at the end.  You may want to put your own wrapper around the library and manage the thread lifecycle yourself.

**Comment by xuezhma** [comment]
Linux version of the library works fine with node-java. I guess the library's OS X version was the problem. Closing this issue.
