### ISSUE TITLE
Could not get the correct/expected return value of the method defined in .java file. (and do we have to compile the *.java files manually every time we modify these files?)

### ISSUE THREAD

**Issue by lxw0109** [joeferner/node-java#326]
I defined a method named `sayHello` in `Hello.java` as follows:
```java
public String sayHello(){
    return "In sayHello()[Hello.java]";
}
```
and in main.js, I want to call this method `sayHello` like this:
```javascript
var helloInstance = new HelloClass();
var returnVal = helloInstance.sayHelloSync();
console.log("Sync: return value of void sayHello(): " + returnVal);
helloInstance.sayHello(function(err, returnVal1){
	console.log("Async: return value of void sayHello(): " + returnVal1);
});
```
But, I got the unexpected output as follows:

```Bash
Sync: return value of void sayHello(): Hello
Async: return value of void sayHello(): Hello
```
Why the return value of the `sayHello` method is always "Hello"(**which seems like the class name**).

How can I get the correct/expected return value "In sayHello()[Hello.java]".
I would appreciate your help.

**Comment by lxw0109** [comment]
I have found the reasons to make this error message happen.</br>
After modifying the `Hello.java` file, I did not compile it manually(`javac Hello.java`). So the `main.js` file always uses the old Hello.class. So the output was unexpected.</br>
However, I have another question, **do we have to compile the *.java files manually every time we modify these files?**.</br>

**Comment by joeferner** [comment]
Yes you'll have to compile each time

**Comment by lxw0109** [comment]
@joeferner OK, thank you. : )
