### ISSUE TITLE
Array of arrays?

### ISSUE THREAD

**Issue by lambrojos** [joeferner/node-java#328]
Hello, I really don't know how I can create a java array of arrays.. should I use some wrapper class such as ArrayList?

**Comment by joeferner** [comment]
Have you tried something like this... 

```
java.newArray("java.lang.Object", java.newArray("char", ['a', 'b']));
```

https://github.com/joeferner/node-java#create-a-char-array

**Comment by lambrojos** [comment]
I am sorry for the late answer, but yes, it works - with some casting on the java side

Thank you
