### ISSUE TITLE
'Could not reserve enough space for object heap' on 32bit JRE (jdk1.7.0_40)

### ISSUE THREAD

**Issue by davewthompson** [joeferner/node-java#350]
All,

Environment: Windows 7 x64
Node: 6.2.1 x32
Node-Java: latest
JDK: x32 jdk1.7.0_40

On running the simple example:

```
var java = require("java");

java.classpath.push("./src");

var MyClass = java.import("com.nearinfinity.nodeJava.MyClass");

var result = MyClass.addNumbersSync(1, 2);
console.log(result);
```

The app just dies with:

```
****** NODE-JAVA RUNNING IN DEBUG MODE ******
Error occurred during initialization of VM
Could not reserve enough space for object heap
```

Any ideas?

Thanks,

Dave

**Comment by davewthompson** [comment]
On adding options such as:

`java.options.push('-Xmx512m -XX:MaxPermSize=128m');`

The app appears to die:

`Process finished with exit code -1073741819 (0xC0000005)`

**Comment by davewthompson** [comment]
Been looking into this. The code crashes at 

`    jclass FindClass(const char *name) {
        return functions->FindClass(this, name);
    }`

This is inside the 1.7.40 jni.h file. According to the Locals, *env is null.

Has anyone else had success running this with Node 6.0.3 against the 32 bit JVM?

**Comment by davewthompson** [comment]
This was a parameter issue; however, the result of JNI_CreateVM is never checked, so any error is swallowed.

Modified code in java.cpp:

`jint result = JNI_CreateJavaVM(&jvmTemp, (void **)env, &args);
if(result < 0 ){
    printf("result: %d\n", result);
}`

...might help anyone having similar issues.

**Comment by ilkyy** [comment]
Hi @davewthompson , is there any solution you find for this issue? 

java.options.push('-Xmx512m -XX:MaxPermSize=128m'); does not working.. 
i had to use 32 bit JVM..
thanks.
