### ISSUE TITLE
String to byte array 

### ISSUE THREAD

**Issue by ccbeloy** [joeferner/node-java#364]
What's the correct way of converting string to byte array. I tried different approaches:
 var getByteArray = function(value){
        var byteArray = java.newArray(
            "byte",
            value.split('')
                .map(function(c) { return java.newByte(String.prototype.charCodeAt(c)); }));
        return byteArray;
    }

or new Buffer("mystring");

But still doesn't work with Hbase SingleColumnValueFilter(byte[] family, byte[] qualifier,..)

**Comment by joeferner** [comment]
What error are you seeing?

**Comment by ccbeloy** [comment]
Joe - I was able resolve this with below code snippet.
var Bytes = java.import("org.apache.hadoop.hbase.util.Bytes");
function getByteArray(str) {
    return java.newArray("byte",Bytes.toBytesSync(str));
}
