### ISSUE TITLE
How to deploy to production servers without compiling ? (Portable Package)

### ISSUE THREAD

**Issue by bozz** [joeferner/node-java#370]
I would like to use node-java in order to use the "jdbc" package for connecting to various databases. Is it possible to somehow make node-java portable - i.e. possible to copy pre-compiled package - since we will not be able to compile node-java on the production servers (no build tools, no python)?

After compiling node-java there are many absolute paths in the generated output - i.e. in build/jvm_dll_plath.json and build/Release/nodejavabridge_bindings.node (and many others). This prevents simply copying pre-compiled package.

What is the recommended way to deploy this package when not able to compile on production servers?

**Comment by joeferner** [comment]
Short of some code changes, you could create a build/test/integration environment that mirrors production, build it there and tar up the results and use that as the deployment artifact.

**Comment by bozz** [comment]
Thanks, so it should be possible if the environment it is compiled on is basically identical to the production environment. 

Which files under /build are actually needed during runtime? As many of them contain absolute paths to the build tools (i.e. Visual Studio on Windows in my case). Is it basically only /build/Release/nodejavabridge_bindings.node?

**Comment by joeferner** [comment]
You'll need to give it a go, I'm not 100% sure

**Comment by bozz** [comment]
Ok, I got it to work. Almost all the absolute paths under /build are not relevant during runtime.

The only thing I needed to update was the path to the JRE under /build/Release/jvm_dll_plath.json.
