### ISSUE TITLE
failed to convert javax.management.openmbean.CompositeDataSupport

### ISSUE THREAD

**Issue by erickyi2006** [joeferner/node-java#371]
When i made a call to jmx.invoke (getMessage) which returns a javax.management.openmbean.CompositeDataSupport, I got an empty {} result in my nodejs.
I think it is the failure to convert  the return result from jmx. 

Has anyone done something similar before?

**Comment by joeferner** [comment]
Many of the returned java objects print like that. Try executing `toStringSync()` on that empty object.

**Comment by erickyi2006** [comment]
Many thanks for the hint. I am able to extract the string results. Brilliant. :)
