### ISSUE TITLE
what are the softwares require for installing node-java in Windows-7 (64-bit)and windows 10???@joeferner

### ISSUE THREAD

**Issue by souravprakashjena** [joeferner/node-java#374]
@joeferner

**Comment by joeferner** [comment]
https://github.com/joeferner/node-java#installation-windows

**Comment by souravprakashjena** [comment]
@joeferner is visual studio installation required for node-java?????

**Comment by joeferner** [comment]
Not sure, I don't have a windows machine. Can you try this https://github.com/nodejs/node-gyp#installation (Option 1 preferably) and let me know how it goes and I can update the readme.

**Comment by souravprakashjena** [comment]
@joeferner  ya with visual studio only its working.....
