### ISSUE TITLE
Could not create class 

### ISSUE THREAD

**Issue by scriptsure** [joeferner/node-java#386]
Anyway point me into the right direction....??? Not sure what i am doing wrong here. on jdk 8... node 6.x... windows.... i have tried com.identrust.otp.authentication.* AND com.identrust.otp.authentication.OTPAuthenticator on import statement but it fails every time on that line...

![image](https://cloud.githubusercontent.com/assets/798281/24664574/074b5fbe-1929-11e7-9adc-0a73fe5fa18b.png)

Could not create class com.identrust.otp.authentication.*
java.lang.NoClassDefFoundError: com/identrust/otp/authentication/*
Caused by: java.lang.ClassNotFoundException: com.identrust.otp.authentication.*
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by unitive-jim** [comment]
Note in the [documentation](https://github.com/joeferner/node-java#api-documentation) it says:

"All items must be added to the options before calling any other node-java methods."

Is your call to push `location` to the `classpath` coming after other `node-java` methods have already been called?

**Comment by scriptsure** [comment]
actually i saw another case that required all the jar to be pushed... then things seemed to work for me... also the way i was instantiating the class was incorrect... NEW did not work for me...

**Comment by joeferner** [comment]
`*` imports are not supported
