### ISSUE TITLE
Node 8

### ISSUE THREAD

**Issue by scriptsure** [joeferner/node-java#387]
Not sure if anyone will know the answer to this yet but... 

Will node-java be able to work in Node 8 when it is released this month?

Aaron

**Comment by joeferner** [comment]
node-java relies heavily on [nan](https://www.npmjs.com/package/nan) so the sooner they support node 8 the better.

**Comment by scriptsure** [comment]
@joeferner Joe sorry you say THEY... you mean node-java? Has there been talk about ensuring it will work with 8.x? Very new to this project... obviously!!!

**Comment by joeferner** [comment]
They as in node-nan developers. If node-nan works with node 8 then node-java should work with node 8. That said node-java works with node 7 which being an odd number is usually the beta for the next even number so I hope it should just work.

**Comment by scriptsure** [comment]
gotcha thanks joe!!!
