### ISSUE TITLE
getStaticFieldValue returns an empty list of strings for list of string constants.

### ISSUE THREAD

**Issue by Droogans** [joeferner/node-java#388]
I'm finding that lists are coming back as empty when testing that my constants are set appropriately on my Java classes.

> node: **v6.9.2**

> java: **version 8, update 121 (build 1.8.0_45-b14)**

> OS: **Mac 10.10.5**

Java code:

```java
public static final List<String> FOOBAR = Collections.unmodifiableList(Arrays.asList("foo", "bar"));
```

Javascript test:

```js
test('public static constant', t => {
    let fieldTypes = java.getStaticFieldValue('com.foo.bar', 'FOOBAR');
    t.deepEqual(fieldTypes, ['foo', 'bar']);
});
```

Will print the following failure message:

```
  1 failed

  valid field types
  ~/code/java/baz/test/foobar.test.js:22

   21:     let fieldTypes = java.getStaticFieldValue('com.foo.bar', 'FOOBAR');
   22:     t.deepEqual(fieldTypes, ['foo', 'bar']);                         
   23: });                                                                     

  Actual:

    nodeJava_java_util_Collections_UnmodifiableRandomAccessList {}

  Must be deeply equal to:

    Array [
      "foo",
      "bar",
    ]
```

Switching the constant to:

```java
public static final String FOOBAR = "foobar";
```

and the test to:

```js
test('public static constant', t => {
    let fieldTypes = java.getStaticFieldValue('com.foo.bar', 'FOOBAR');
    t.deepEqual(fieldTypes, 'foobar');
});
```

Passes as expected.

**Comment by joeferner** [comment]
Some Java types are not directly converted to JavaScript object but instead kept as proxy objects. In the first example calling `fieldTypes.sizeSync()` or `fieldTypes.getSync(0)` would get items from the list.

**Comment by Droogans** [comment]
If you have a getter/setter pair that gets/sets a list of something, you'll need to apply this same strategy to get the number/string/boolean/etc. that java-node understands as well.

Although I do wish it converted lists and arrays to javascript array objects, as well as maps -> plain old javascript objects.
