### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by izikorgad** [joeferner/node-java#401]
Hi,
We are having a severe issue when running our app on Amazon Linux 4.9.27-14.33.amzn1.x86_64.
We are getting segmentation fault error that crashes the whole Node.js process.
It occurred when executing the following line:
var Properties = java.import('java.util.Properties');

Can you please assist?

**Comment by joeferner** [comment]
Duplicate of https://github.com/joeferner/node-java/issues/399
