### ISSUE TITLE
Installation failure for both node v8.9.1 and JDK 8

### ISSUE THREAD

**Issue by stuartZhang** [joeferner/node-java#416]
D:\Node_Labs\github_projects\json2proprietary>npm install java --save

> java@0.9.0 install D:\Node_Labs\github_projects\json2proprietary\node_modules\java
> node-gyp rebuild

D:\Node_Labs\github_projects\json2proprietary\node_modules\java>if not defined npm_config_node_gyp (node "C:\Users\StuartZhang\AppData\Roaming\nvm\v8.9.1\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  java.cpp
  javaObject.cpp
  javaScope.cpp
  methodCallBaton.cpp
  nodeJavaBridge.cpp
  utils.cpp
  win_delay_load_hook.cc
**C:\Users\StuartZhang\.node-gyp\8.9.1\x64\node.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x296852 [D:\Node_Labs
\github_projects\json2proprietary\node_modules\java\build\nodejavabridge_bindings.vcxproj]**
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\StuartZhang\AppData\Roaming\nvm\v8.9.1\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\StuartZhang\\AppData\\Roaming\\nvm\\v8.9.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Node_Labs\github_projects\json2proprietary\node_modules\java
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\StuartZhang\AppData\Roaming\npm-cache\_logs\2017-11-14T15_12_05_998Z-debug.log

**Comment by stuartZhang** [comment]
It's interesting that node-java v0.9.0 does work with both node v8.9.0 and JDK 8.

**Comment by stuartZhang** [comment]
I have just discovered

<Windows 10 + JDK 8 + nodejs v8.9.1> fail to install.

However,

<Windows 7 + JDK 8 + nodejs v8.9.1> succeed to install.

The MSBuild installation comes from "npm install --global --production windows-build-tools"

**Comment by stuartZhang** [comment]
The issue has been resolved by re-installing the module "windows-build-tools" for nodejs v8.9.1

npm install --global --production windows-build-tools

My summary is as below:
1. nvm install 8.9.1
2. nvm use 8.9.1
3. npm install --global --production windows-build-tools (Per nodejs version, the module must be installed respectively)
4. npm install java

**Comment by krisbaehr** [comment]
@stuartZhang I'm running into the same issue. Can you elaborate on the fix? What do you mean by nvm install 8.9.1?
