### ISSUE TITLE
sun.awt.CGraphicsEnvironment call opens a GUI window and hangs

### ISSUE THREAD

**Issue by relsqui** [joeferner/node-java#422]
I'm using node-java to get at the [SikuliX](http://sikulix.com/) API. My scripts work fine on Windows; on Mac, the first time I try to instantiate a class, it seems to open a tiny GUI app and then hangs until that app is closed (at which point it also closes -- the script does not resume).

Here's a minimal repro:

```javascript
var java = require('java');
var path = require('path');

// this jar is generated by the SikuliX installer
java.classpath.push('sikulixapi.jar');

// changing which class we instantiate doesn't appear to change the result
var screen = java.newInstanceSync('org.sikuli.script.Screen');
console.log('this is never reached');
```

Here's what pops up when I run that -- the taskbar icon, app menu, and about box:

<img width="56" alt="screen shot 2018-03-05 at 2 13 04 pm" src="https://user-images.githubusercontent.com/1859500/37003600-7eac1d6c-2082-11e8-8c16-dd528ae7d899.png">  <img width="232" alt="screen shot 2018-03-05 at 2 13 33 pm" src="https://user-images.githubusercontent.com/1859500/37003606-83d8876c-2082-11e8-9034-b8a596450fe8.png"> <img width="310" alt="screen shot 2018-03-05 at 2 13 41 pm" src="https://user-images.githubusercontent.com/1859500/37003612-8786b7f8-2082-11e8-92c9-20fe2fb3f511.png">

Now, this only happens with SikuliX and not other packages ... but it also only happens when running through node-java (the Sikuli IDE and command line script runner both behave as expected). Also, this unwanted app describes itself as node, which is why I suspect that node-java itself is involved (although I'll check in with the SikuliX maintainer also).

Any ideas about what might be going on?

(I'll add information below as I try things.)

---

Noticed #21 and tried adding `java.options.push('-Djava.awt.headless=true');`. This fixes the immediate problem, in that the weird popup doesn't happen and the script can proceed, but it also breaks later because it's trying to interact with a screen that it doesn't know exists. So this isn't a long-term solution, but it might help narrow down what's wrong.

Also, if I command-click in the dock to see where the mystery app is, it claims to be /usr/local/bin (not "be in," _be_), which ... raises more questions than it answers.

---

The SikuliX Launchpad thread for this question is here, if that's helpful: https://answers.launchpad.net/sikuli/+question/665279

~Notably, if I add `java.options.push('-Dsikuli.debug=3');` to get debugging output from SikuliX, I see nothing regardless of what the script is doing -- is it possible that's getting eaten by node-java somewhere along the line?~ Never mind, just user error here.

**Comment by relsqui** [comment]
Just noticed I can command-click in the dock to see where the app is (I'm new to Mac, heh) and it claims to be `/usr/local/bin`, which ... raises more questions than it answers.

**Comment by RaiMan** [comment]
As mentioned at Launchpad: it must be:
 `java.options.push('-Dsikuli.Debug=3');`

Sorry, my fault (the lowercase .debug)

**Comment by RaiMan** [comment]
Apparently there is a problem in the approach of node-java on Mac with the Java 
`GraphicsEnvironment.getLocalGraphicsEnvironment()`
which is the base to evaluate the accessible Graphics devices (screens, printers, ...).

The implementation in this area is system dependent:
on Mac we have the implementing class
`sun.awt.CGraphicsEnvironment`
which in turn internally accesses some native libraries.

The offending code in SikuliX seems to be (not executed, if java.awt.headless=true):
```
GraphicsEnvironment genv = GraphicsEnvironment.getLocalGraphicsEnvironment();
GraphicsDevice[] gdevs = genv.getScreenDevices();
```

The problem is known here since 2012 and not solved yet:
https://github.com/joeferner/node-java/issues/422

**Comment by relsqui** [comment]
@mgc found a solution for this! Adding:

```javascript
process.env['JAVA_STARTED_ON_FIRST_THREAD_' + process.pid] = '1'
```

allowed me to import and use Sikuli through node-java. I'll add this to the other thread and close this one (since it is, at this point, a duplicate).
