### ISSUE TITLE
Upgrade lodash to 4.17.13 after a security patch

### ISSUE THREAD

**Issue by relsqui** [joeferner/node-java#478]
Lodash recently [fixed a vulnerability](https://github.com/lodash/lodash/pull/4336); can the node-java lodash dependency be updated to 4.17.13?

Checked to see if I could just make the PR, but I can't get the tests running locally (unless they're intended to run a long time without output, heh) and I didn't want to submit the change if I couldn't verify it.

**Comment by humphreyn** [comment]
I would suggest to upgrade to lodash v 4.17.14

**Comment by relsqui** [comment]
I see this is done in #480, just waiting on a release. :)

**Comment by relsqui** [comment]
Thanks!
