### ISSUE TITLE
Installation fail - jdk-15.0.1 - jvm_dll_path.json

### ISSUE THREAD

**Issue by ouassimBenMosbah** [joeferner/node-java#518]
I tried to install node-java but the installation failed because the generated jvm_dll_path.json didn't have the good version. It did generated ";C:\\Program Files\\Java\\jdk-15.0.1\\bin\\server" instead of ";C:\\Program Files\\Java\\jdk-14.0.1\\bin\\server"

**Comment by dbouchierarcad** [comment]
if you want to use another version than the version installed on your environment, you need to create the JAVA_HOME environment variable:
in a terminal if you don't have this environment variable node-java uses the version defined with the java -version command

java -version => java version "11.0.10" 2021-01-19 LTS
JAVA_HOME => C:\Program Files\Java\jdk1.8.0_271
PATH => add this C:\Program Files\Java\jdk1.8.0_271\bin

![image](https://user-images.githubusercontent.com/60424217/109774814-0a076380-7c01-11eb-9914-2e366c98f8e1.png)
