### ISSUE TITLE
Vulnerability in async dependency

### ISSUE THREAD

**Issue by RakhimAimaganbetov** [joeferner/node-java#577]
Guys, can you always keep the `async` dependency up to date?

Or can you use a higher version of `async` than 2.6.3 in the next release, please? We would like to avoid `npm audit` warnings.

Thank you in advance!

**Comment by AsifImam** [comment]
JFROG vulnerability scan also picked this up with following info
In Async before 2.6.4 and 3.x before 3.2.2, a malicious user can obtain privileges via the mapValues() method, aka lib/internal/iterator.js createObjectIterator prototype pollution.
Request to publish a new package with this vulnerability fixed. Thanks.

**Comment by RakhimAimaganbetov** [comment]
The developers of "async" confirm that the vulnerability has been fixed on their website, and ask you to update the version of the dependencies. 

Can I ask you to publish a new release with an update of the "async" dependency? Thanks!

**Comment by RakhimAimaganbetov** [comment]
Here is a new node-java [version](https://www.npmjs.com/package/java/v/0.14.0) which contains a fix for the issue described above.
