### ISSUE TITLE
require('java') fails with "Error: The specified module could not be found."

### ISSUE THREAD

**Issue by dsulcer** [joeferner/node-java#73]
Hi,

I'm fairly new to node.  Windows 7, node v0.10.20, express 3.3.4, node java 0.2.5, Java 1.7.05, Visual Studio 2010.  I have had luck with node, express, mongo etc in small test projects.  Am experimenting with integrating with a particular Java API.  

I was able to run "npm install java" in a small sample project without any errors (after some hiccups).  I'm trying to verify that it's working correctly by starting with a small main.js, which after errors I stripped down to a simple:

   var java = require("java");
   console.log("Ok it ran");

This fails with 

D:\dev.node\dev\asimplejava>node main

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.
D:\dev.node\dev\asimplejava\node_modules\java\build\Release\nodejavabridge_bindi
ngs.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\dev.node\dev\asimplejava\node_modules\java\lib\nod
eJavaBridge.js:5:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

I seem to have a file called nodejavabridge_bindings.node in the place it's expecting it to be (d:\dev.node\dev\asimplejava\node_modules\java\build\Release).

I tried "npm install -g java" without any difference.  

I saw a comment on another issue, for a different native module, about making sure the NODE_MODULE macro matches binding.gyp but I don't know how to use that information or if it is relevant. 

Any ideas what I am doing wrong?  Thanks in advance for any help.

**Comment by souravprakashjena** [comment]
@dsulcer  how you fix the above issue ???
