### ISSUE TITLE
Mavericks Issue?

### ISSUE THREAD

**Issue by xjamundx** [joeferner/node-java#86]
I'm not a Java expert, but I am having this issue.

```
~/dev $ npm install java@0.2.7
npm http GET http://npm.paypal.com/java/0.2.7
npm http 200 http://npm.paypal.com/java/0.2.7
npm http GET http://registry.npmjs.org/java/-/java-0.2.7.tgz
npm http 200 http://registry.npmjs.org/java/-/java-0.2.7.tgz

> java@0.2.7 install /Users/jamuferguson/dev/node_modules/java
> node-gyp rebuild

  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../src/java.cpp:2:
../src/java.h:7:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^
1 error generated.
make: *** [Release/obj.target/nodejavabridge_bindings/src/java.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jamuferguson/dev/node_modules/java
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

```

Here is my version number and stuff

```
~/dev $ which java
/usr/bin/java
~/dev $ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)
```

**Comment by loretoparisi** [comment]
@kevinrc I'm having this error on `macOS Sierra` and idk 1.8, did you experienced it on recent models of MPB and java8?

**Comment by nselikoff** [comment]
I was experiencing a similar issue, although the file that couldn't be found was `jni_md.h`. Turns out, if you're using `jenv` (https://github.com/gcuisinier/jenv), because it uses a shim and symlink for `JAVA_HOME`, `node-java` will resolve the path to "Users" not "Library" and therefore won't include the extra `darwin` subdirectory (where `jni_md.h` is located).

**Comment by nicholasren** [comment]
I'm using `jenv`and run into the exactly same problem @nselikoff  mentioned above.
My current workaround is copy `jni_md.h` and `jawt_md.h` from `<JDK_HOME>/Contents/Home/include/darwin` to  `<JDK_HOME>/Contents/Home/include` and run `npm install java`

**Comment by parminder7** [comment]
@nicholasren I am also using `jenv` and tried your recommended solution, but I am still getting ```../src/java.h:7:10: fatal error: 'jni.h' file not found
#include <jni.h>``` error. What do you suggest to do next?

**Comment by paulwcy** [comment]
Setting JAVA_HOME worked for me
`export JDK_HOME=$(/usr/libexec/java_home -v 1.8)`

**Comment by mustafabutt-dev** [comment]
I am also facing this issue with the following specs: 
node --version
v21.1.0

java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 1.8.0_381-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.381-b09, mixed mode)

```
npm ERR! ../src/java.h:7:10: fatal error: 'jni.h' file not found
npm ERR! #include <jni.h>
```
