### ISSUE TITLE
System.exit(0) makes the main process exit with exit code 0

### ISSUE THREAD

**Issue by gfhuertac** [joeferner/node-java#99]
This is related to #92 
We are running an action hero app and testing it with Mocha.
On one of the tests we call System.exit(0), following what is specified on #92. But this causes the main process exits with exit code 0, so the test tool to think that the build was successful even though there were failures on the testing process.
Is there any way to capture the System.exit from the parent process?
I already tried with process.on('exit', .... but it was never called.

**Comment by joeferner** [comment]
Unfortunately it doesn't look like there is a way to block System.exit without using a security manager.
